### ISSUE TITLE
Restyle user name in menu bar

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#101]
To improve usability, we need to restyle the username in the top nav bar. People often don't find that this is a drop down menu.

**Comment by dottorer** [comment]
It should look like this: 
![image](https://cloud.githubusercontent.com/assets/14217285/12578714/0c543de8-c423-11e5-87d9-f319054893b0.png)

**Comment by dottorer** [comment]
This might be a good one to improve usability

**Comment by anvarik** [comment]
@dottorer here is a look: 

<img width="186" alt="screen shot 2016-02-03 at 11 49 31 am" src="https://cloud.githubusercontent.com/assets/1272279/12781331/0320edaa-ca74-11e5-8115-851b3176ec38.png">

**Comment by dottorer** [comment]
Nice - perfectly done! Thanks! We can get a PR out for it...

**Comment by anvarik** [comment]
@dottorer it is already there #114
