### ISSUE TITLE
Restyle 'add' button in top menu bar

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#102]
Users cannot identify the (+) symbol as a button to add new tasks or supplies. More so, it sometimes get squished by the browser in the layout.

We need to replace it with a more intuitive control to add new items to the system.

**Comment by dottorer** [comment]
Instead of

![image](https://cloud.githubusercontent.com/assets/14217285/12578919/1d4b7976-c424-11e5-852a-25214a9dcc5d.png)

we should go for a better approach:
1. Have a square button with the word '+  New...'
2. Have a drop down menu with radio button which items to add (Task or Supply)
3. Have an action button with 'Create...' or 'Cancel'

![image](https://cloud.githubusercontent.com/assets/14217285/12578860/d77e3fa0-c423-11e5-9fc7-b135e93d7f23.png)

**Comment by dottorer** [comment]
@anvarik Maybe following on the success of the user restyling, you want to look at this challenge? Bit more involved but not much more than the user name nenu we already have...thoughts?

**Comment by dottorer** [comment]
I think it is better ti just havea drop dien menu like under the username and not have check boxes and a create/ca cel buttons. Let's keep it simple...

**Comment by dottorer** [comment]
Hmmmm, re-reading it, this is what is left for mvp1. I guess I had bigger plans at some point, but for now it would be:
1. in the top bar offer a nicely styled square orange button saying [(+) New...]    so a plus icon (little smaller and the text 'New...'
2. then this simply drops down the menu as is today...

I don't have too much styling mojo right now, but we need to make it more intuitive for users to find the 'add'.

**Comment by dottorer** [comment]
@kristysnet : Here is a screenshots of the button in IE11:

![image](https://cloud.githubusercontent.com/assets/14217285/13497139/287f0004-e154-11e5-89f5-3790b1fad5ef.png)

Note it is on the right side of the leftnav divider line and also doesn't scale to the text there...sorry if this is fiddly but we need it to be properly scalable...can you take a look?

**Comment by dottorer** [comment]
@kristysnet / @phil-monroe I was playing around with this new button layout more and have a few thoughts:
1. The real label should be 'Add', not 'New'. Sadly, this without a dispute translates in German into the ugly 'Hinzufügen' (we can thank Microsoft for the terminology). 
2. If the label gets so long, it overlaps the circle name on the left. We cannot move the button to the right of the line between the left nav and the main area since we show the 'Back to...' message there and plan to use it for the search box. Therefore we could experiment with putting it in the left nav above the first 'My Tasks' item. It could look somewhat like this example:
![image](https://cloud.githubusercontent.com/assets/14217285/13553306/2efd38c8-e385-11e5-8bb3-8ab872df609f.png)
3. The style still looks clunky to me and not crisp. How about we try using the word 'Add' first and then the plus icon in a white circle just like in the screenshot.

**Comment by kristysnet** [comment]
@dottorer Restyled the add button in branch feature/add_button_rev2. Please have a look and let me know if you want me to make further changes.

**Comment by dottorer** [comment]
Hi Kristy, here is what I see right now:

![image](https://cloud.githubusercontent.com/assets/14217285/13576677/2ba10c44-e48f-11e5-907c-ce53f7d6c95f.png)
 
This has the restyled button, but the location is still the same. I was thinking more along the lines of:

![image](https://cloud.githubusercontent.com/assets/14217285/13576838/e0041f32-e48f-11e5-986a-d57f1763c4b4.png)

And in this case, we could use the exact same font strength as the leftnav items such as 'My Tasks' (just in white). Can we try this?

**Comment by dottorer** [comment]
Having said that, I am not sure how the drop down menu will look if we place it there as it might overlap the leftnav items in a weird way.

Adding @phillipoertel for thoughts. Boy do we need a UX guy to do the pretty picture for us :-)

**Comment by dottorer** [comment]
@kristysnet : Alternatively and likely easier and quicker for now is the following option:

![image](https://cloud.githubusercontent.com/assets/14217285/13577450/cbd45c86-e492-11e5-8508-5f0a5d9b48ae.png)

This would required the following:
- do not show add button when we display a single task or supply. This is when we show 'Back to all tasks' in that spot.
- do not show when we display the helper list.
- only show when we are either on the circle dashboard or on the work group dashboard. This is likely where people will take action and really 'Add' something new. 

It is likely not ideal that buttons come and go when navigating, but this might be a good compromise for right now. 

Note that we should still improve the font by making it the same as the leftnav fonts (in white) and also ensure that the little plus icon is in a circle, not an oval. 

What do you think?

**Comment by kristysnet** [comment]
@dottorer sorry about that, i misunderstood before and thought you wanted to try the restyle/text change first before trying to move location. No worries though, I think your latest idea is better for mvp1 anyway. I will implement this this afternoon.

**Comment by kristysnet** [comment]
@dottorer feature/add_button_rev2 should now show the add button in the back button area. Also, the font should be the same as the side nav items.
