### ISSUE TITLE
Feature: Rework the options for sourcing helper for a task (assign, suggest, invite)

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#104]
Currently we have 2 different buttons to send an invitations email to (a) only the work group of the task and (b) the entire circle. This is not intuitive yet and could be much improved by the approach outlined in the spec here: https://docs.google.com/document/d/1hetDLs0m49u01nKNkhfQzBw02lw-Dthw3sxChr2ztkk/edit#.

**Comment by dottorer** [comment]
This now includes #141 which has been asked for by multiple pilot users...

**Comment by phillipoertel** [comment]
Unassigning can now be previewed on the review app. It won't work until the mailer template en/task/task_unassigned is created, though.

**Comment by dottorer** [comment]
task_unassigned templates are done and pushed to Mandrill. Will test unassign feature next.

**Comment by phillipoertel** [comment]
@dottorer merged and deployed on staging. Some German translations are missing, let me know if they should be there, then we'll investigate.
![bildschirmfoto 2016-06-14 um 18 20 49](https://cloud.githubusercontent.com/assets/5188/16050689/dfaa10b2-325c-11e6-8308-d7296f6adcda.png)

**Comment by phillipoertel** [comment]
@dottorer some i18n keys have changed though, so maybe all is good.

**Comment by dottorer** [comment]
@phillipoertel added translations for DE and tested in staging - looking great so far. This is a major new feature and improvement to the platform and I am very excited we got it in now. Will close as 'awesome' now and potentially open bug issues if they arise....THANKS!
