### ISSUE TITLE
Improve edit page for working groups

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#105]
The current default edit page for working group is clunky and needs love.

![image](https://cloud.githubusercontent.com/assets/14217285/12579286/2bb33d20-c427-11e5-9544-2843576c05c8.png)

We need to:
1. add a description of 200 chars max. (this needs to be shown below the title in the WG dashboards)
2. better picklist for workgroup organizer (label needs to read like that as well).
3. We need to allow for more than 1 organizer. This will require a different picklist UX. Ideally we could have a spot to add / remove organizers by user of their member icon -> e.g.  (RS) icon.
![image](https://cloud.githubusercontent.com/assets/14217285/12579397/eeec469c-c427-11e5-90fe-5a4f3536deed.png)
When clicking on the (+) icon, we don't add the current user, but we offer a list of all circle members to pick from.

4. Later we will also implement the flag to mark a work group 'private' as in #81.

**Comment by dottorer** [comment]
Example of how the top title should have a description in small print: 

![image](https://cloud.githubusercontent.com/assets/14217285/12648774/cf91cabe-c5db-11e5-881b-8d4aa5431f71.png)

This basically applies to any page that has a big font title and then a smaller sub-script text giving explanation...

**Comment by dottorer** [comment]
@diegoaad @ajaysagar Maybe a good simple one to test the dev skills....

**Comment by dottorer** [comment]
@anvarik this could be a good one?

**Comment by ajaysagar** [comment]
@anvarik @dottorer .. I have already started working on this, shall I pick a different one ?

**Comment by dottorer** [comment]
If you started, then go ahead and continue. Assign issue to you if you work on it to avoid confusion. Will look for another for anvarik

**Comment by ajaysagar** [comment]
will do, sorry about that.

**Comment by dottorer** [comment]
@ajaysagar Could we consider this for mvp1 for end of this week? Should hopefully be small beginner work...

**Comment by ajaysagar** [comment]
@dottorer, will try to finish it by tuesday latest.

**Comment by dottorer** [comment]
Let's mark this complete for now. The prompt for multi-select of several work group organizers is really hard to grasp, but so be it for mvp1. Also the missing translations of the page header is tracked in #108 so we should lock this down.
