### ISSUE TITLE
Missing translatable strings for mvp1

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#108]
This issue tracks strings I could not yet find in the yml files to translate. We need to externalize them so I can get at them.

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/12751992/8c3c7514-c9c0-11e5-8887-e874d016612c.png)

drop down values in task_scheduled_time_type

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/12752271/05da488c-c9c2-11e5-9cfc-2d3204888dd7.png)

On user profile:

home and mobile phone
user_public_profile field

**Comment by dottorer** [comment]
Note that I have translated strings for those already present, they somehow do not yet get picked up from the model values...

**Comment by dottorer** [comment]
@ajaysagar This one seems to be for the working group edits:

![image](https://cloud.githubusercontent.com/assets/14217285/12752601/9beb6904-c9c3-11e5-9eac-627a4f5ecc78.png)
 
Still unclear why some of the strings are not picked up by the translations in the system...weird!

**Comment by dottorer** [comment]
On circle Admin Pages:

![image](https://cloud.githubusercontent.com/assets/14217285/12752666/e4f2ce8a-c9c3-11e5-87b1-77bde47f751c.png)

**Comment by dottorer** [comment]
New member sign up page:
![image](https://cloud.githubusercontent.com/assets/14217285/12753811/e7a5d88e-c9c8-11e5-9772-0f0b27cd406d.png)

**Comment by dottorer** [comment]
@diegoaad i did another round of translation checking and looks like exactly what we have listed now is still pending extraction into strings....just fyi...

**Comment by dottorer** [comment]
@kristysnet: Diego will not find the time as he is headed to Brazil. Could you take a look at exposing these last strings?

**Comment by kristysnet** [comment]
@dottorer The missing strings (at least for english) on the sign up page should have been addressed in a pull request that was merged last night. Were there any other pages you wanted me to look at to add missing translation strings to?

**Comment by dottorer** [comment]
@kristysnet 

Sign up screen looks good. This leaves us with:

1. Schedule values from the base_form.rb of tasks:
![image](https://cloud.githubusercontent.com/assets/14217285/13280435/553fd054-dade-11e5-83f3-e0a81615012d.png)

2. Heading in the working group page (hardcoded)
![image](https://cloud.githubusercontent.com/assets/14217285/13280460/791abc32-dade-11e5-934a-279ddb6eee6e.png)

**Comment by phil-monroe** [comment]
Just needs another round of translations:

```
activerecord.attributes.task.scheduled-time-select.at	
activerecord.attributes.task.scheduled-time-select.between	
activerecord.attributes.task.scheduled-time-select.on_date	
circle.working_groups.edit.header	
supplies.flash.already_taken	
supplies.flash.complete_failed	
supplies.flash.completed	
supplies.flash.decline_failed	
supplies.flash.declined	
supplies.flash.invite_failed	
supplies.flash.invited	
supplies.flash.volunteer_failed	
supplies.flash.volunteered	
user.account.edit.country_select	
user.account.edit.update_settings	
user.account.show.edit_profile	
user.account.show.reset_password	
user.account.show.title	
user.account.show.view_public_profile
```

**Comment by dottorer** [comment]
Done for German and in trans 5 branch. Awaiting Pierre's French text to drop in as well.

**Comment by dottorer** [comment]
Added March 1 translations for DE and FR in feature/trans6 branch.
