### ISSUE TITLE
Make layout of supply like task layout

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#109]
We have an inconsistent layout between the two actionable items.

![image](https://cloud.githubusercontent.com/assets/14217285/12753202/64858d70-c9c6-11e5-95ee-58324ea67a35.png)

The supply tracks:
1. organiser is listed twice it seems
2. the helper that signed up for the supply is shown in the main area, not on the right.
3. the action buttons on the right should have the same layout as for action tasks:
![image](https://cloud.githubusercontent.com/assets/14217285/12753282/ab86c00e-c9c6-11e5-89d2-8accaf2cfd16.png)
3.1 the top field should show the helper that sigend up for the supply. We don't have a minimum/maximum of required helpers, so the title could read 'Supplied by % helpers' and then we list the initials icon underneath.
3.2 the email button to invite the group / circle should go in that box.
3.3 the other action buttons should remain under that box.

**Comment by dottorer** [comment]
Maybe this could be a good one for @kristysnet ? I looked at the code and it seems like a straight forward carry over from what we do on tasks.

**Comment by dottorer** [comment]
Bonus credits would be related #120 ...:-)

**Comment by dottorer** [comment]
This could be a good ine for @nolanchan...

**Comment by NolanChan** [comment]
hi @dottorer , is there any way that I could get English screenshots? I'm a little confused on how the instructions line up with the pictures. Also, what's the difference between the 1. and 3.1?

**Comment by dottorer** [comment]
@NolanChan Here you go:
![image](https://cloud.githubusercontent.com/assets/14217285/13899809/5e67daa6-edf7-11e5-93c4-c1b8f9c7d96a.png)
 
You are correct that (1) is part of 3.1. Today with supplies we only allow 1 helper to deliver it. However, in reality multiple helpers could drop of a donation. We do not need to specifcy a number of helpers required (like we do on tasks), but if we allow more than one helper to assign this supply to themselves, it would be a step forward. 

That means: we would not show the singular 'Helper' name on the left, but provide several of the helper initials icons on the right. Each helper can self-assign and self-unassign to the task. The button 'I don't have this supply' would be shown only to helpers that are currently assigned to the supply. And to add themselves to the supply, they can click the (+) icon as we do on tasks.

This isn't very precise guidance, but maybe you can play with it a little bit in a local build and see what you feel is a good solution. Ping me for any further clarifications.

**Comment by dottorer** [comment]
This has actually been mostly addressed by a series of changes. Closing.
