### ISSUE TITLE
Cannot signup new user even if T&Cs box is checked

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#113]
![image](https://cloud.githubusercontent.com/assets/14217285/12779724/eb80094c-ca69-11e5-968c-b3a027f25c0b.png)

Seems like it is not accepting the boolean value for the T&Cs.

**Comment by dottorer** [comment]
Added this bug to track down...

**Comment by phil-monroe** [comment]
@dottorer fixed the issue but i have a followup question: should the public profile checkbox be presented on the account create page? I am assuming no just to get people into the system. The can always go back and check it after they understand the system and what it means.

**Comment by dottorer** [comment]
Correct, it should not be displayed during signup, but be set as 'YES' as default (Diego is working on that). User should basically opt-out if they need to.

**Comment by dottorer** [comment]
@phil-monroe Maybe we can just feed the 'yes' value into the form without even showing it. Then Diego would not have to modify anything as it would be set during signup.

Also, I noticed we currently show the flag which we would not do in the end.
