### ISSUE TITLE
Route new member signup to admin for approval

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#122]
Once we open up the platform for anyone who discovers a circle to sign up /this is our goal!), we need to ensure that the administrator (a) knows about it and (b) has the option to activate the account. We need to make this optional and add a flag on the circle definition for 'new helpers require approval'. 

If approval is mandated, this requires a new workflow whereby the newly signed up helper first receives an email saying his registration is being processed by the circle admin. Then we need to alert the admin to look at his list of pending registrations and approve (1-click). Once approved the new member gets an email notification that she can now sign in and use the system. 

Until that point, the new helper is a pending helper. Pending helpers can not log in to the system; when trying they will be presented with a screen telling them their request is pending. Once approved, they receive an email that they can now login.

**Comment by dottorer** [comment]
@phil-monroe Per our discussion this is now for mvp2...

**Comment by dottorer** [comment]
This might be a must-have soon even if we envision the "join" Url as the main means of onboarding. @phil-monroe How much work do you think this would be? I am envsioning:
1. flag to make this active for a circle
2. routing of pending activations to circle admin.
3. email to new signee to let them know they will ne reviewed
4. UI for the admin to accept / decline new signee
5. email to user with result

**Comment by dottorer** [comment]
Created email templates in MailChimp for en/de.

"en/user/account_activation"
Variables:
*|FIRST_NAME|*
*|HELPER_CIRCLE|* 
*|APPROVE_REQUEST_URL|*

"en/user/account_activated"
Variables:
*|FIRST_NAME|*
*|HELPER_CIRCLE|* 
*|CIRCLE_LOGIN_URL|*

**Comment by phillipoertel** [comment]
Updated spec from discussion with Ralf yesterday:

- if user activations are pending, the circle admin sees a number behind "Administration" in the sidebar.
- the circle admin invite page gets a table with pending users, showing name, email, signup on and an approve/decline button. The table _only_ shows pending signups.
- pending users can't use lale, instead they get a message like "Your account is currently being activated. Please contact the circle admin ..."
- circle admin is notified of new signups by email
- new user is notified of activation
- optional: add a setting, if users are active immediately (old way) or need to be activated first.

**Comment by phillipoertel** [comment]
@phil-monroe here are my thoughts. It's a draft, I may still be missing something.

1. add state attribute on User:

- DB migration to add user.state
- add to User: "enum state: [:pending, :active, :rejected]"
- DISCUSS: add "validate :state, inclusion: [:pend...]", too? Allow nil for state?

2. set user pending after signup:

- assign :pending state in User::Create::Submit#execute

3. pending users can't use lale:

- add before_action :ensure_active_user to ApplicationController
- have this action run everywhere login is required
- it redirects to login, displays message "... account waiting for approval."

4. circle admin can activate pending users:

- fetch pending users with current_circle.users.pending, show in a table
- user activation button goes to (new) User::ActivationController and uses (new) User::Activate mutation
- DISCUSS: decline-button goes to User::ActivationController and uses (new) User::Activate mutation. Or make separate controller & mutation?
- alternatively:
	- activation/decline go to User::AccountController and change state. 
	- need to use CanCan to ensure circle admin did that. 

TBD Phillip:
- look into how the pending state may affect other places of the code
- check if/how a state machine would help here. User states will be nil, pending, active, declined.

**Comment by phillipoertel** [comment]
@ralph @phil-monroe a first version of the happy path for this feature is currently deployed on staging, if you would like to have a look.

Still to do:
- rather than logging out a pending user after choosing a circle, show him/her a decent page and message
- implement decline action (to discuss)
- refine UX when accepting pending members (to discuss)
- make sure only active members are shown in all user lists on lale
- preserve deep link login (generally can't deeplink when user needs to login first)
- allow the circle admins to configure if new members need to be activated or not
- add feature specs for this workflow

**Comment by phillipoertel** [comment]
Feedback by @dottorer (will be in English again next time ;-))

1. Es läuft schon alles echt rund - well done! Keine hard stops bisher.
2. in der 'your request is being reviewed' page sind oben rechts links zu 'Angemeldet als XYZ' und 'Helferkreis KH' und Abmelden. die aber alle nichts bringen. Den Link zum HK und Abmelden sollten wir wegmachen. Weniger ist mehr.
3. Wenn es pending requests gibt ,zeigen wir in der leftnav die (1). Das ist super. Wenn man aber die 'Verwaltung' aufmacht, weiss man nicht mehr, in welchem Tab man was tun muss. Vielleicht können wir hinter 'Invite helpers' ein 'Invite helpers*' in the tab name machen oder einen roten Punkt oder badge mit (1). Kommt ja häufig vor im UX.
4. Die Email muss ich besser betiteln, denn der button sagt 'Approve' was nach auto-approve sich anhört. Besser ist hier 'Review pending request'. Mach ich gleich.
5. NIT: wenn der request approved ist, verschwindet er sehr elegant aus dem grid. Aber in der leftnav ist noch die (1), die mit dem nächstne refresh weg ist. Falls man das gleich glatt machen möchte.
6. in der 'Join' page ist der 'other helpers can see my profile' check nicht abgefragt. Der default ist Yes und Helfer können sich dann im System später mehr abschotten. Ich frage mich, ob wir so durchkommen oder den flag gleich zeigen müssen. Sollten wir besprechen...
7. Der tab extended settings sollte als zweites nach basic settings kommen.

**Comment by phillipoertel** [comment]
@dottorer 

1. thanks!
2. done
3. done
4. todo Ralf
5. done
7. done

UI stuff tested in all browsers I have on my Mac (current Chrome, Firefox, Safari), and deployed to staging.

**Comment by dottorer** [comment]
point 4. done! Also added translated email templates for DE and pushed them to Mandrill. Will ping Pierre to do French, but we can close this out for now and open issues as they arise.
