### ISSUE TITLE
add Lale logo in app for branding

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#123]
We need to provide the correct logos in the app pages for branding. See details below.

**Comment by dottorer** [comment]
Add (logo+name) to sign-in and sign-up page in top header:
![lalelogocolor180](https://cloud.githubusercontent.com/assets/14217285/12841869/4d7122ea-cbef-11e5-83c1-95b7425e7c15.png)

**Comment by dottorer** [comment]
Add icon-only to the left nav footer corner in the app itself (this should link to the website lale.help):
![laleiconcolor60](https://cloud.githubusercontent.com/assets/14217285/12841927/be8b44b0-cbef-11e5-8d8f-22c040182b62.png)

**Comment by phil-monroe** [comment]
@kristysnet can you pick this up?

**Comment by dottorer** [comment]
Looks great. Thank you!
