### ISSUE TITLE
http://lale.help/ homepage for English locale has German Impressum in footer

### ISSUE THREAD

**Issue by pjfanning** [lale-help/lale-help#124]
http://lale.help/de/impressum appears beside other English language links for 'Contact Us'.

**Comment by dottorer** [comment]
Thanks for finding that - at this point the legal requirement for an 'impress' is only for Germany, however I have seen sites having it appear in both languages. I might split it out in 2 pages. What would a good English title be for that content?

**Comment by pjfanning** [comment]
Hi Ralf, I'm not an expert but I think it might be best to omit the link in the English language version. the content does not appear to be something that normally appears on English language web sites. Or if does, it tends to be a general Contact or About Us page.

**Comment by dottorer** [comment]
I removed the link from the english footer for now, as less is more. We still have it from the German version. Thanks!
