### ISSUE TITLE
In sign-up, emails should not be considered case-sensitive.

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#126]
Right now you can sign up the same user twice with:

k1@ecologicalstrategies.de

and again with

K1@ecologicalstrategies.de

We need to make this unique regardless the case.

**Comment by dottorer** [comment]
Here is what we got in the database: 

![image](https://cloud.githubusercontent.com/assets/14217285/12871473/7a750b6e-cd7d-11e5-9e13-71572627c42d.png)

**Comment by dottorer** [comment]
Another issue arose, found by @diegoaad : 

Some users are created without having a user.identity. Apparently when we created user i1, we set the email without @ (we specified i1€ecologicalstrategies.de) and this bypassed the required email validation, but never really created an identity.

We need ot tighten up the whole process of initially creating valid users or we will end up with issues in the app later.

**Comment by pjfanning** [comment]
In the PostgreSQL db defintion, we could declare the email columns as 'citext' for case insensitivity.
http://www.postgresql.org/docs/current/static/citext.html

**Comment by dottorer** [comment]
This is not quite working as intended. A user can have their own way of entering their email address when registering, and it should be stored as such. However, we need to enforce uniqueness on the lower case based version. 

**Example:**
RALF@lale.help
ralf@lale.help
ralf@Lale.help 
 
should all log me in into the same account. However a user might prefer to enter it in a specific way and it should not be blocked from logging in (it looks like we think RALF@lale.help is not valid when we store ralf@lale.help).
