### ISSUE TITLE
Users directed to wrong login page / user stuck at login

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#130]
There seems to be something wrong with the URL / page we return when sending people to staging.lale.help.

A tester used the 'join' URL from an email, but instead of getting the signup form to enter their name, etc they were shown the login form (which makes no sense for them).

Also, when returning users try to hit the root URL, they end up at the 'Find a circle' page which makes no sense.

Multiple browsers were used (IE, FF, Chrome) and cache was cleared. Any ideas?

**Comment by phil-monroe** [comment]
This is due to session expiration of 15 minutes and is reproduced via:
1) user creates account and joins circle A
2) user leaves site for longer than 15 minutes
3) user receives email with join link
4) user visits join link with expired session
5) user redirected to login page since they had a session, but it was expired.

So if the user had logged in, then re-visited the join url, everything would be fine.

@dottorer: how do you expect this to work with session timeout? Since the url is not unique to the user, we cannot auto log them in.

**Comment by dottorer** [comment]
@phil-monroe hmmm, this sounds like an complex sequence. It feels like we triggered this much simpler. For example, my sister (our tester) used IE for the very first time and entered the Lale root URL (https://staging.lale.help/). Noone was authenticated before in IE (even clreaed cache etc later on). When entering this URL, we do not get the sign in page, but we are redirected to the page of the map where the user can look for different circles. Also, another user is shown as signed on. It almost appeared as if some pending state on the site itself was being used when this brand new user tried to get in. 

I know this is unlikely, but we got stuck much simpler than the 15 min expiration sequence above. I will try to do more replication to pin it down...

**Comment by phil-monroe** [comment]
woah... thats freaky... when you have chance we shoul pair on that via Screen Hero. I'm really interested in how that is happening.

**Comment by dottorer** [comment]
@phil-monroe The user data in Staging are this are in circle 'Helferkreis baml'. 

Bernd Helfer - baml3@gmx.de -> Password- HK03baml  (Circle admin)

Heidi Helfer -> baml1@gmx.de -> Password HK01baml

Heinz Helfer - baml2@gmx.de -> Password HK02baml

None of these can log in right now, it seems. Also we receive no error message at all on the login screen which is weird. Lastly, this has been tested in IE and mostly Firefox (which seems to not run smooth).

**Comment by phil-monroe** [comment]
@dottorer: The only thing that I could find wrong for those users was that their passwords you listed were incorrect. I just reset their passwords, and they can now login just fine.

**Comment by dottorer** [comment]
Hmmm, i guess that is good, i could not even find ther user-identity. Wil try again now.

**Comment by dottorer** [comment]
I tried this again right now and I could not login for the first user above (baml3@gmx.de). This is the circle admin and it seems still hosed.

The second user (baml1@gmx.de) is passing the sign in screen, but then taken to the 'Find circles near you' page, where they can pick other circles, but not the intented 'Helferkreis baml' one. Note tha this user was originally created by following the the 'join' URL for the intended circle, so they should not be unassociated right now. More so, the intended circle is not listed on the map as I believe they are missing the geo location. I will send you what I see in the dataclips as well.

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/13257739/56fc2a16-da50-11e5-8f84-2ca063502a2d.png)

@phil-monroe I believe the two helper baml1 and baml2 do not have a valid primary_circle_id hence they are stranded somehow. This is where we get stuck i believe.

**Comment by dottorer** [comment]
This seems to be working better now and we should consolidate the effort on #147. Will close this and create a clean one should issues occur in testing.
