### ISSUE TITLE
Remove "location" approach from circle and user

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#137]
While the concept of location and geocode is very relevant in the "find a circle" flow, it makes little sense in the regular capture of key objects like circle and helper. In fact, it seems to frequently cause issues if no valid location is resolved. More so, users have consistent issues understanding what to enter there.

Given this, we need to remove location (at least visibly, we might track it internally). Instead we should have a simple address object composed of fields:
Street
Postalcode
City
Country (prompt list)

This would be used for the circle (replacing location) and for helper profile.

**Comment by dottorer** [comment]
@phil-monroe added this for mvp1, do you think this is something kristy could tackle?

**Comment by phil-monroe** [comment]
should now be remove from users, but still needs to be fixed for circle's and tasks

**Comment by phil-monroe** [comment]
Should be fixed now. Feel free to reopen if there is anything missing.
