### ISSUE TITLE
Access Control

### ISSUE THREAD

**Issue by phil-monroe** [lale-help/lale-help#14]

**Comment by tmandke** [comment]
```ruby
    # Circles
    user.can :manage, Circle, admin: user

    # Work Groups
    user.can :manage, WorkGroup, circle: { admin: user }

    # Tasks
    user.can :manage, Task, working_group: { circle: { admin: user } }
    user.can :volunteer, Task, working_group: { circle: user.circle }
```

@jamesfan @stephanerangaya These were the access controls I could remember of so far.
Plz advice If I got any wrong or missed any.

**Comment by dottorer** [comment]
Looking at the ability class and trying to interpret it, it seems that:

1. Everyone can read circles and create them, if they are not yet linked to one.
2. For users that have a circle associated, 
2.1 they can update + destroy if they are admins.
2.2 read workgroups in the circle
2.3 c/u/d workgroups as well as tasks only if they are the circle admin
2.4 sign up for tasks in a work group only if you are member of the circle
2.5 cannot volunteer someone else to do a task??
2.6 can complete a task if it is assigned to you.

Is this a correct English read on the definition in ability.rb? If so, I can review this in detail and layout the specs for a complete access control definition.

Also, how does someone become circle admin? By creating it, i assume. Correct? Is there an equal notion of work group admin (by creation?).

**Comment by tmandke** [comment]
@dottorer  FYI I updated ur comment so it reads easier following markdown format (for sub-bullets just 2 spaces and it considers them sub bullets)

You are correct on all accounts. 
In terms of admins currently there is only the notion of one admin for a circle. This admin controls everything. I will have to agree that this need to change but with this PR I want to get access control setup for what we have currently.

**Comment by tmandke** [comment]
made a quick update 
1. Everyone can read circles and create them, if they are not yet linked to one.
2. For users that have a circle associated, 
  1. they can update + destroy if they are admins.
  2. read workgroups in the circle
  3. c/u/d workgroups as well as tasks only if they are the circle admin
  4. sign up for tasks in a work group only if you are member of the circle
  5. cannot volunteer someone else to do a task??
  6. can complete a task if it is assigned to you :new: __and not yet completed__ :new:.

**Comment by phil-monroe** [comment]
@tmandke: re: can complete a task if it is assigned to you :new: and not yet completed :new:.

Once we get the concept of an "organizer" for a task, is should probably be the organizer or volunteer who can complete a task

**Comment by tmandke** [comment]
makes sense

**Comment by tmandke** [comment]
Closing this issue And lets followup with more specific issues to add more access control.
