### ISSUE TITLE
Allow work group organizer to assign task to work group member

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#141]
Often a work group organizer already knows someone to take on a task (or they have previously talked about it). In that case, they should have a way to make any group member an assignee of the task.

This would require:
(a) prompt to select from work group members to fill an assignment spot
(b) email notification to new assignee using 'task suggestion' email template with the option to decline the task.

**Comment by dottorer** [comment]
@kristysnet this would be an important improvement to how tasks are actually allocated in real life. I heard this numerous times by now as a requirement. We have the task suggestion email in place, which we would need to tweak only a bit. Main item here is a highly usable prompt to select work group member for assignment. Your ideas on this would be much appreciated, we should get that in soon for pilot users, i believe.

Maybe @phil-monroe has a suggestion on how to make this nice and intuitive.

**Comment by dottorer** [comment]
@kristysnet I think this is really part of #104 which you were already looking at. I recently completed a more complete specification document in that issue so we could review this together and discuss in which increments this can meaningfully be implement. If you have ideas, this could be a good one for us with @phil-monroe in our next dev huddle.

**Comment by dottorer** [comment]
Closing this as included in #104 to keep the issues clean.

**Comment by dottorer** [comment]
Re-opening this to get done outside of #104 since it is such an urgent user request.

**PART 1:**
When switching to a tabbed view on task edit (in #307), we need to introduce a tab called 'Helpers' which allows the work group / task organizer to select helpers to assign them for the task.

A) for open group, they can pick any helper in the circle
B) for closed groups, the can only pick group members

**PART 2:**
Also we need to send a notification email to the helper to tell them that they have been assigned to this task / or unassigned. 

**PART 3:**
Lale bot needs to write down 'xxxx has assigned yyyy to this task on ddddd' (or unassigned) to track what happened.

**Comment by dottorer** [comment]
@phil-monroe This is in the ball park of reworking the task edit in #307 and it would be a huge help to introduce this ability. Every group organizer has basically asked for it by now and I was hoping to do a complete rework of the 'invite' function but that is too much work so I am hoping to get this in earlier. Doable?

**Comment by dottorer** [comment]
@phillipoertel Putting this up for discussion on Monday for the next sprint as part of #104. Let's find out what can best be built...

**Comment by phillipoertel** [comment]
@dottorer do you consider the assignment of a volunteer as a task change, i.e. should all existing volunteers be notified of the change?

**Comment by phillipoertel** [comment]
@dottorer please ignore the last comment. That behavior already exists (other volunteers _are_ notified), so I won't change anything about it.

**Comment by phillipoertel** [comment]
@dottorer I made good progress on the sourcing rework. The assign task feature is still missing the mandrill template but I believe it should be done on my part, and can be tested on: https://lale-help-stg-pr-348.herokuapp.com/circles/1/tasks/1.
Make sure to create all three mailer templates {de,en,fr}/task/task_assigned before testing, otherwise nothing will happen because the backend throws an error.

**Comment by phillipoertel** [comment]
![bildschirmfoto 2016-06-10 um 21 41 15](https://cloud.githubusercontent.com/assets/5188/15976593/14133e70-2f54-11e6-9983-16aee2305a00.png)
And how could anything go wrong with these volunteers? ;-)

**Comment by dottorer** [comment]
en/fr/de temapltes for /task/task_assigned are created. 

Note: it should actually always fall back to the en template without error if the others are not found. Does that not that way?

**Comment by phillipoertel** [comment]
Strange; I'll have to check that on Monday. The implementation isn't any different from the other mailers, so it should just work.

**Comment by dottorer** [comment]
Completely delivered in #104
