### ISSUE TITLE
Join URL not working 

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#147]
When using the join URL such as https://staging.lale.help/join/3-helferkreis-kirchheim it fails on location (see rollbar).

[lale-help-stg] staging - New Error: ActionView::Template::Error: undefined method `location' for #<User::Create:0x007ff85ec59578> https://rollbar.com/lale-help-stg/lale-help-stg/items/71/

**Comment by phil-monroe** [comment]
fixed!

**Comment by dottorer** [comment]
Re-testing this with a new circle. Issue condition was by following the 'Join' URL for a new helper circle, I am taking to the correct page inviting me directly to the new circle. 
https://staging.lale.help/join/25

However, the new user **does not enter an address**, and therefore is not taken into the circle directly but to the 'Find circle' page:
https://staging.lale.help/public/circles

When using the join URL, there is no need to look for a circle, we were invited to one specific one.

@Matthias-Lale is testing this as well for more commentary. Does this happen there as well?

**Comment by dottorer** [comment]
More so, if I go back and enter an address near that circle, I get the following page:
![image](https://cloud.githubusercontent.com/assets/14217285/13393654/28e7965a-dee3-11e5-9d7a-740b548d6699.png)

I seemed to be signed on as the new user (Detlev), but it is asking me to correct an error but not showing any fields....?

**Comment by dottorer** [comment]
Also, the Join page does not offer the 'show my profile to all circle members' check box which we must offer here.

**Comment by phil-monroe** [comment]
I fixed the issue with form errors preventing a user from joining a circle, but cannot seem to reproduce the redirect to https://staging.lale.help/public/circles... 

I'm closing this out for now, @dottorer or @Matthias-Lale feel free open a new issue if the public circles redirect still exists, but please include more detailed steps to reproduce.
