### ISSUE TITLE
Task Comments

### ISSUE THREAD

**Issue by phil-monroe** [lale-help/lale-help#15]

**Comment by dottorer** [comment]
Adding to Tejas as we had discussed this on slack. I think we only have the v2.0 UX design for comments. 
![task details 4 2x 1](https://cloud.githubusercontent.com/assets/14217285/11372070/d5112a22-92cb-11e5-9426-57f4370cdb4b.png)

@stephanerangaya might have a version of this with the current UX applied. We need to distinguish between the important comments of helpers and the status updates (assigned to helper1 on date1, unassigned from helper1 on date2, closed on date3 by helper4, etc.). I think status changes are important, but discussions between users even more. So real estate usage will be critical to show the right stuff...

**Comment by dottorer** [comment]
@tmandke forgot to add the design for adding comments. Similarly, we need to provide a form of editing or removing a comment by the author.

If we can make it look stylistically as outlined by Stephane, but use the new color scheme of the app, it would be great!

![task details 3 2x 1](https://cloud.githubusercontent.com/assets/14217285/11392223/8b951dbc-9358-11e5-8d35-b7415ad3e325.png)

**Comment by tmandke** [comment]
@stephanerangaya can u provide updated mocks for comments?

**Comment by dottorer** [comment]
Task comments feature is implemented, tracking bug fixes in #77 and edit / delete in #80 and comment styles in #79.
