### ISSUE TITLE
On supply email, first user wins, others do not have feedback

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#151]
Example: 

we send our invite email to source a supply in work group 'Begegnung'. All members receive the invite with the 'I have this' button.

First user 'user2@lale.help' clicks the button and the supply is assigned to him.
Second user 'user4@lale.help' clicks button in his email, then it taken to the supply page where it still shows 'user2' assigned. However, he now has the button 'I don't have this after all' showing up for him, which is incorrect.

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/13294171/0d1e1746-db23-11e5-8566-7e205b87cc8b.png)

This is user4 (Karl May)

**Comment by dottorer** [comment]
Strnage enough, if a third user (one that is admin) being ralf@lale.help (Ralf admin) also clicks the 'I have this' button, he snaps the supply away from the first guy:

![image](https://cloud.githubusercontent.com/assets/14217285/13294367/f6bee77c-db23-11e5-8ee3-4b64bcfd9d5e.png)

**Comment by dottorer** [comment]
@phil-monroe I think the right way to handle this is to implement something more along the lines of #109 where multiple helpers can sign up to donate a certain item. In the scenario used we need 8 sleeping bags and folks could bring 1 or more each...

**Comment by phil-monroe** [comment]
Currently, supplies are designed to be tied to a single volunteer. The latest update ensures only one volunteer can claim a supply. 

Is having supply quantities and multiple volunteers required for MVP1?

**Comment by phil-monroe** [comment]
Closing this bug out for now. We can add multiple volunteers to supplies as apart of #132.

**Comment by dottorer** [comment]
Agreed that we can close this for mvp1 and re-visit the whole way of dealing with supplies as a real feature overhaul....
