### ISSUE TITLE
French email templates not being used for French user.

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#152]
We now have French templates for all email, but they don't seem to be picked up for French language users.

![image](https://cloud.githubusercontent.com/assets/14217285/13294301/944d4d72-db23-11e5-9e6e-c11dffd23e74.png)

Title is in French, but template is not used:
![image](https://cloud.githubusercontent.com/assets/14217285/13294322/ae99fa7c-db23-11e5-89fa-504fbeb99d1c.png)

**Comment by phil-monroe** [comment]
@dottorer: none of the french templates were pushed from Mailchimp to Mandrill.

**Comment by phil-monroe** [comment]
I pushed all of the french templates and verified in my local dev that french templates work.

**Comment by dottorer** [comment]
@phil-monroe sorry totally my bad, i forgot about the mandrill push when I cloned the templates - duh!
