### ISSUE TITLE
From task, we get link back to 'All tasks' which should be 'All open tasks'

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#159]
When viewing a task, we can navigate back to 'All tasks' but we replaced this page with the 'All open tasks'. We should change the link and show the label 'Back to Open Tasks'

![image](https://cloud.githubusercontent.com/assets/14217285/13320998/d2e579d4-dbcc-11e5-999c-4e8ee73a17dc.png)

**Comment by kristysnet** [comment]
Fixed this in feature/task_back_button. I made the link go back to where ever the user clicked on the task from (or supply). That way if they click a task from the circle dashboard, the back button goes back to the circle dashboard. We may want to update the back button text to be more generic to match this (circle.tasks.show.back and circle.supplies.show.back). Maybe have it just say 'Back to tasks' or something. Or, I can just revert this and have the link go back to open tasks, totally your call.

**Comment by dottorer** [comment]
@kristysnet this is a great solution. Please assign back to me so ican ensure i update labels and translation...

**Comment by phil-monroe** [comment]
@dottorer: just needs the translations and this is done.

**Comment by dottorer** [comment]
Translated in branch trans9 and merged in stg.
