### ISSUE TITLE
Task header color does not match task dot color

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#160]
We have a mixup of color between how we render the dot in from of a task in the task list and how we color the header. Today we have:

NEW TASK: dot = light blue / header = light grey
ALLOCATED TASK: dot = black / header = light blue (!!!)
URGENT TASK: dot = red / header = depends on status
CLOSED TASK: dot = green / header = green

What we need to have is consistency with (code changes required marked in **bold**):
NEW TASK: dot = light blue / header = light **blue**
ALLOCATED TASK: dot = **dark grey** / header = **dark grey**
URGENT TASK: dot = red / header = **red**
CLOSED TASK: dot = green / header = green

**Comment by phil-monroe** [comment]
fixed!
