### ISSUE TITLE
Supply does not change dot or header color according to status.

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#161]
Even if a supply is already assigned to a helper to deliver, it shows grey. 
![image](https://cloud.githubusercontent.com/assets/14217285/13321402/19dbf1e0-dbcf-11e5-8061-3f5e4b5e21d5.png)

We should follow the same approach as for tasks and do:
NEW SUPPLY: dot = light blue / header = light blue
ALLOCATED SUPPLY: dot = dark grey / header = dark grey
URGENT SUPPLY: dot = red / header = red
CLOSED SUPPLY: dot = green / header = green

(note also that Closed supplies are no longer visible and ideally should for now be listed under the 'completed tasks' page in a separate section for supplies)

**Comment by kristysnet** [comment]
@dottorer fixed the new/allocated/closed statuses to reflected the correct header colors in the feature/dot_header_colors branch. I don't see any logic in the application that defines 'urgent' tasks/supplies though. What makes a tasks/supply 'urgent'? Or is that a future feature?

**Comment by dottorer** [comment]
I think we have a way to determine when to show the dot as red. It is something like not fully allocated with less than three days to go. Also unusually high number of comments can nark something as problematic. Phil would know the exact function in the code...

**Comment by phil-monroe** [comment]
fixed!
