### ISSUE TITLE
Nit: Better icon for number of comments needed

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#162]
We currently re-use the little compass icon from the existing font set, but this was only a stop gap. 

![image](https://cloud.githubusercontent.com/assets/14217285/13321540/daf70db0-dbcf-11e5-9877-3f07303c0919.png)

It confuses users and we should replace it with

![image](https://cloud.githubusercontent.com/assets/14217285/13321534/cbc02f20-dbcf-11e5-8502-ef0d6637ab6d.png)

**Comment by kristysnet** [comment]
Should be fixed in IE 11 now
