### ISSUE TITLE
On circle dashboard, organizers are listed multiple times

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#163]
If a user is organizer of more than one work group, we list them multiple times in the 'Organizers' box. This is not helpul here:

![image](https://cloud.githubusercontent.com/assets/14217285/13321635/80f0f8f2-dbd0-11e5-9c99-06f4fa025590.png)

**Comment by dottorer** [comment]
Writing up nits by now to apply spit and polish :-)

**Comment by dottorer** [comment]
@kristysnet  Also note on the screenshot that work groups can have the same name (they are unique by Id I guess). This will happen rarely but we might rule it out and make the WG name unique. Just noticed it and don't want to pollute the issue, let me know if you want a separate one.

**Comment by kristysnet** [comment]
@dottorer Would you like working group name to be unique across the board, or on a per circle basis?

**Comment by dottorer** [comment]
@kristysnet unique within circle is what we need. thanks!
