### ISSUE TITLE
Sign up flow broken on location field

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#165]
Per https://rollbar.com/lale-help-stg/lale-help-stg/items/72/ we currently cannot have a new person sign up for Lale (which we need for the very first admin user to start the whole thing).

**Comment by dottorer** [comment]
@phil-monroe @kristysnet 

Looks like there is a glitch on location. Note that we should not require an address necessarily as user should be able to sign up 'light' with email / password. In order to find an existing circle, we should have them enter a search string in the location field to show existing circles on the map. 

When they create a new circle, they must specify a full address as a required set of fields. However, the individual helper is not required to enter their address. 

Note also that the sign up is not yet wrapped in a transaction as mistakes in the first form already lock up the user email address. But we are working on correction the unit of work here.

**Comment by phil-monroe** [comment]
Should be fixed now. Feel free to reopen with steps to reproduce if there is another way this fails.
