### ISSUE TITLE
When creating a new task in a new work group, error occurs

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#172]
We created a brand new work group and opened the very first task. Saving causes the following error:

```
at=info method=POST path="/circles/18/tasks" host=staging.lale.help request_id=6d0c06c5-2e08-4e03-b0d7-4dae9690bbaa fwd="93.204.98.251,162.158.94.91" dyno=web.1 connect=1ms service=245ms status=404 bytes=2348 
Feb 29 07:29:05 lale-help-stg app/web.1:  ActiveRecord::RecordNotFound (Couldn't find WorkingGroup without an ID): 
```

Seems like a working group ID is missing?

**Comment by dottorer** [comment]
Really odd behaviour, when hitting the back button from the error page, the edit form of the new task shows the task name entered in the due date field ?!?

**Comment by dottorer** [comment]
It seems also that the value for work group is not changeable (the wg organizer has only one work group). It appears grayed out and not changeable by drop down. This might have to do with the recent fix for delegated tasks.

**Comment by dottorer** [comment]
Confirmed: when a user has more than one work group to organize, the prompt is open and I can select one of the 2 groups. Then saving the task works. Therefore it appears that the grayed out value in the scenario above is shown, but not persisted.

**Comment by phil-monroe** [comment]
The current implementation is: If *any user* that can create or edit a task can
only do so for only a single working group, then the select box will be disabled
and force selected to the only working group they have access to.

For example: a helper is a working group organizer for only one working group.
In this case the user can create new tasks but cannot assign a different working
group. The tasks can only be created for their assigned working group.
Is this not the right behavior?
On Mon, Feb 29, 2016 at 7:52 AM, Ralf Schroeder <notifications@github.com>
wrote:
It seems also that the value for work group is not changeable (the wg organizer
has only one work group). It appears grayed out and not changeable by drop down.
This might have to do with the recent fix for delegated tasks.

—
Reply to this email directly or view it on GitHub
[https://github.com/lale-help/lale-help/issues/172#issuecomment-190266039] .[https://github.com/notifications/beacon/AAsJ3dbkY4bp2rhaDZ3ZkxAq2cBhOvj4ks5pow9MgaJpZM4HlhUu.gif]

**Comment by phil-monroe** [comment]
Ahh, if that's the case I bet I know what is going on.

On Mon, Feb 29, 2016 at 8:00 AM, phil@philmonroe.com <phil@philmonroe.com>
wrote:
The current implementation is: If *any user* that can create or edit a task can
only do so for only a single working group, then the select box will be disabled
and force selected to the only working group they have access to.

For example: a helper is a working group organizer for only one working group.
In this case the user can create new tasks but cannot assign a different working
group. The tasks can only be created for their assigned working group.
Is this not the right behavior?
On Mon, Feb 29, 2016 at 7:52 AM, Ralf Schroeder <notifications@github.com>
wrote:
It seems also that the value for work group is not changeable (the wg organizer
has only one work group). It appears grayed out and not changeable by drop down.
This might have to do with the recent fix for delegated tasks.

—
Reply to this email directly or view it on GitHub
[https://github.com/lale-help/lale-help/issues/172#issuecomment-190266039] .[https://github.com/notifications/beacon/AAsJ3dbkY4bp2rhaDZ3ZkxAq2cBhOvj4ks5pow9MgaJpZM4HlhUu.gif]

**Comment by dottorer** [comment]
I think the behaviour you outlined above with a single WG as organizer is correct, it should be defaulted to that unchangeable. Problem is it crashes when we do that :-)
