### ISSUE TITLE
Provide better guidance to user when login fails

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#188]
Right now, when a user is not entering the correct email / password into the sign in page, there is not message and the page just gets refreshed. This can lead to frustration and we should give some overall hints as to what could have gone wrong. We need to balance this with a security aspect of not giving too many hints to hack the site, but we need to help the users with generic things to consider.

**Comment by dottorer** [comment]
Example of what XING sends you:
'Bei der Eingabe Ihrer E-Mail-Adresse/Ihres Kennworts ist ein Fehler aufgetreten. Bitte beachten Sie, dass Sie sich ausschließlich mit Ihrer aktivierten E-Mailadresse einloggen können. Ebenso muss die Gross- und Kleinschreibung des Passwort berücksichtigt werden.'

'An error has occured when entering your email and password. Please remember that you can only log in with a valid and activated account. Also ensure to check upper and lowercase with your password.'

**Comment by dottorer** [comment]
Per conversation with @phillipoertel entering this for mvp2 consideration.

**Comment by phillipoertel** [comment]
@dottorer deployed a fix on staging. Need to discuss if the flash message should stay down there, IMHO it's not very visible.

**Comment by phillipoertel** [comment]
Let's show some guidance info (uppercase / lowercase; CAPS LOCK)

**Comment by phillipoertel** [comment]
Changes as discussed with Ralf:
- display red div below the form
- fade it in/out
- don't show flash in the corner

**Comment by phillipoertel** [comment]
@dottorer above changes can be tested on staging.

**Comment by dottorer** [comment]
@phillipoertel looking good, i will do translation next and we can push to prod once tested.

**Comment by dottorer** [comment]
Translation done in branch, awaiting merge.

**Comment by dottorer** [comment]
Translation done, reassigning to Phillip for flash styling and then merge.

**Comment by dottorer** [comment]
I believe this is completed, with some UX fixes in #221
