### ISSUE TITLE
Not permission to complete action puts task in weird state

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#189]
This is around taks: https://staging.lale.help/circles/3/tasks/73 

I tried to close out the task, but I got the flash message 'user does not have permission to complete action' or something similar. I am logged in a user4@lale.help who is working group organizer of the group that this task is in. Therefore I think it is correct to offer the option of 'Close task' Note also that this task is delegated to the user 'C. Matze Walz' as task organizer. That could have implications on this issue. 

Can we verify what conditions are used to determine whether or not to show the 'close' button and what happens after this when processing the closing? We might have a mismatch.

**Comment by dottorer** [comment]
Note that on second try user4@lale.help was able to close the task. Might have been a timing / warm-up issue?

**Comment by phil-monroe** [comment]
we will keep an eye out for it. let me know if it keeps happening.
