### ISSUE TITLE
Notifications via Email

### ISSUE THREAD

**Issue by phil-monroe** [lale-help/lale-help#21]

**Comment by dottorer** [comment]
This will be an important feature for mvp1. Most of the current users are informed of tasks via emails and we can support a successful pilot by keeping that. We need to define:

1. format, style, tone, layout of the emails -> can be a simple clone of how slack does it.
2. frequency of email: a. when a tasks is assigned to you / modified and b. when it is within 24 hours of due date. c. after completion with a link to mark it complete.

We don't need to have all the features of email notifications ready but if we get a basic smpt server integration and mail template, this shows the direction.

**Comment by dottorer** [comment]
Changing to reflect we will do in-app inbox later. Closing this as working now.
