### ISSUE TITLE
Add organizer to workgroup is missing - in Safari 8.0.3 (works in firefox et al)

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#219]
Somehow the option to add an organizer for a work group has gone missing. We need to add it back asap and put to PROD as users are stuck at this point.

**Comment by kristysnet** [comment]
@dottorer this should be restored in master branch now. let me know if you want me to push out to staging.

**Comment by phil-monroe** [comment]
@dottorer: I cant seem to replicate this in any environment. I even "became" a prod user that seemed to have the issue and could not replicate. @kristysnet was thinking you meant the multiselect we had before private groups on the main settings page of a working group.

I can edit organizers by going to the organizers tab in the working group settings.

![screen shot 2016-03-14 at 8 20 19 pm](https://cloud.githubusercontent.com/assets/723421/13766886/0ad8a622-ea23-11e5-92a5-eff9e0d38f92.png)

Are you sure that the user is on the right tab of the working group settings? 

Just a note: the drop down is not shown if there are no other members available to be added to the working group members/organizers list. aka: all users in the circle are a member/organizer of the working group.

**Comment by dottorer** [comment]
So we don't want the old multiselect back. But i did a skype with Tasha yesterday where i confirmed the issue and could not set her as a group organizer. I will try to replicate today again and provide more precise rep instructions, if still persisting.

**Comment by dottorer** [comment]
@phil-monroe I debugged this with Tasha today. This is indeed a problem with Safari 8.0.3 that does not render the drop down list and add button to pick a workgroup organizer. We switched to firefox and it was all shown as expected.

Strange only that you tested this in Safari as well and it showed up....

**Comment by kristysnet** [comment]
@dottorer can you send a screenshot of the missing elements? I'm not seeing anything obvious in the code and I have no way of pulling up the site in an older version of safari.

**Comment by dottorer** [comment]
Dont think i have a screen shot fron Tasha but it is showing the 'No volunteers' message for the list but nothing under it. So the dropdown list of helpernames and the button are not appearing.

**Comment by dottorer** [comment]
Setting Prio to low; don't want to be chasing browser ghosts unless the users report this in a clearly replicable way...putting on hold for now...

**Comment by dottorer** [comment]
Closing as 'Could not reproduce'...
