### ISSUE TITLE
Show env indicator for STG and DEV environments

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#220]
When debugging issues and testing stuff, it is sometimes useful to know which environment a screenshot was taken from and what release. Can we display a small indicator of env plus commit hash like 'STG -  a5d24a0' in the footer section.

This would not be shown in PROD.

**Comment by dottorer** [comment]
Maybe something @NolanChan watns to look at? :-)

**Comment by dottorer** [comment]
@NolanChan looking good! Only thing is we might style it a bit smaller, cursive and space it away from the existing Lale text. Right now it is kind of bunched into it...but great work!

**Comment by dottorer** [comment]
Closing for now, better styling can be applied as we go....

**Comment by NolanChan** [comment]
Oh, I don't mind getting to this, this weekend. Should I submit the PR under this issue?

**Comment by dottorer** [comment]
@NolanChan Sure, i reopened the issue for now and you can add a new PR for the stylings. Thanks!

**Comment by dottorer** [comment]
Completed
