### ISSUE TITLE
Nit: Admin cannot open public profile for pending users

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#225]
![image](https://cloud.githubusercontent.com/assets/14217285/13806500/4ba4eac8-eb5c-11e5-955f-ac80bb782f3b.png)

In the list of pending join requests we show a link to the public profile, which does not yet work for the admin. Ideally we can make this work so the admin can review the details of the user.

**Comment by NolanChan** [comment]
Sorry @phillipoertel , didn't mean to take your Issue :\

**Comment by dottorer** [comment]
changing assignee to @NolanChan as he seemse to have addressed this in #232. Once reviewed and merge, we can close this out.

**Comment by dottorer** [comment]
Seems to be working now - thanks @NolanChan

**Comment by dottorer** [comment]
I rhink this is fixed now...
