### ISSUE TITLE
Helper photo in profile and helper icon

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#227]
once we have #53 completed, we need to enhance the helper profile page to allow for upload of a photo.

Photos need to be adhering to a minimum pixel size in width and heigth (min 180x180 seems standard), limited in file size (1 MB?), and cropped to fit into a round circle icon.

An example of this was done in the mockup by @stephanerangaya 

![image](https://cloud.githubusercontent.com/assets/14217285/13807515/b7c30ae6-eb61-11e5-8c51-698160a9d775.png)

Helpers needs to be able to change and also remove a photo from their profile page. 

If a photo is uploaded, it should be displayed in the helper icon everywhere instead of the initials.

**Comment by dottorer** [comment]
Unclear as to how much work the whole cropping and centering of images is, hoping there are some standard libraries to help with that stuff (like [this](https://infinum.co/the-capsized-eight/articles/best-rails-image-uploader-paperclip-carrierwave-refile)).

**Comment by dottorer** [comment]
@kristysnet Adding this one into the mix. It would be really neat to have the helper photo finally in the platform. Maybe talk to  @phil-monroe to get a sense of how to do this best and what the effort would be. Seems like every platform has this so likely there are existing gems to handle all the imagery stuff....

**Comment by dottorer** [comment]
Long time in the wish list - come out great! Thank you @phillipoertel !!!!

**Comment by Matthias-Lale** [comment]
Hi Ralf,

 

sehr schön, hat bei mir gleich funktioniert. Jetzt wollte ich das Bild ändern, hat auch geklappt. 

 

Aber es zeigt auf dem Profil, wenn man auf „Bearbeiten“ klickt immer  an „keine Datei ausgewählt“, auch nach dem neu eingefügten Bild.

 

 



 

 

Von: Ralf Schroeder [mailto:notifications@github.com] 
Gesendet: Freitag, 13. Januar 2017 12:33
An: lale-help/lale-help
Cc: Subscribed
Betreff: Re: [lale-help/lale-help] Helper photo in profile and helper icon (#227)

 

Long time in the wish list - come out great! Thank you @phillipoertel <https://github.com/phillipoertel>  !!!!
