### ISSUE TITLE
Ability for an admin to block / unblock a user account in their circle.

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#240]
Should abuse of the system in violation with the terms be detected by the administrator, they need to disable a user account in Lale which will prevent future login for such user. 

This needs to be possible to also re-activate a user if the problem has been cleared.

**Comment by dottorer** [comment]
The UX for blocking a user can be from the user's public profile:
![image](https://cloud.githubusercontent.com/assets/14217285/14943456/3964618e-0fda-11e6-81fa-26c3ddd65b4c.png)
* the 'Block' button is only available to admins.
* if a user is pending activation, it could be done from here as well by the admin (not top prio but nice)
* we should allow admins to put comments on a user. Only other admins can see these. This is where they could track the history leading up to the blocking and possibly comments as to why the user was unblocked.
* If a user is blocked, the button would offer 'Unblock' 
* All blocked users are also shown in the administration console:
![image](https://cloud.githubusercontent.com/assets/14217285/14943472/b687202a-0fda-11e6-9a1d-5c766bae5b70.png)

* If users are blocked, they can no longer log in. They will be shown a page similar to the 'pending activation page' saying that their account has been blocked by the admin and they should contact him for resolution.

Ultimately, the admin should have a 'Delete' button on the same page in order to purge a user from the system (as also offered to the user in #42). This will complete the user account state cycle.

**Comment by phillipoertel** [comment]
Further info:
- when an admin deactivates a user, the status will be :blocked
- when a user disables his account, it will be :disabled (a user can disable circles on his profile)
- when a user is blocked but the blocked circle is still in session[:circle_id]. In that case redirect to the user's next circle if there is one

**Comment by phillipoertel** [comment]
@dottorer FYI I just deployed my WIP. For simplicity, it's in the same staging app as the user pending/activate refactoring: https://lale-help-stg-pr-316.herokuapp.com
There are still some things missing, don't bother testing yet if you don't like to.

**Comment by dottorer** [comment]
Working in STG now....
