### ISSUE TITLE
List updated fields on task in comment history (Lale-bot) and also send out in task mailer as merge var

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#249]
We will leverage the existing "comments" functionality to also display status changes of tasks/supplies as outlined in #298. But when a user changes a specific value on a task, we need to have 'the Lale system' post comments about the exact changed fields in the existing comments thread as follows:

![image](https://cloud.githubusercontent.com/assets/14217285/14109623/2c2c2528-f5c3-11e5-83d7-b0bce77ca23a.png)

**Comment content:**
1. comma-separated list of all changes fields + "has changed."
Ex: "**Title**, **Due Date** and **Number of required Helpers** has changed."

Also, the same string of changed field names must be passed to the task mailer class as a merge variable for the task_change mailing.

**Comment by dottorer** [comment]
This should be similar to concepts in other systems, such as Trello for example:
![image](https://cloud.githubusercontent.com/assets/14217285/14109864/5cab2266-f5c4-11e5-90a7-14ee4a0f9395.png)

**Comment by dottorer** [comment]
This will be also used by @phillipoertel  in #216 to display which task a new task was cloned from.

**Comment by phillipoertel** [comment]
The mailer merge variable is TASK_CHANGES. It contains a string with the changed field(s) localized to the recipient's language. Examples: "Name und Beschreibung", "name and description".

Implemented (lale bot comment and mail merge var) and deployed to staging.

**Comment by phillipoertel** [comment]
@dottorer should I do the auto comments for supplies as well? So far, all lale bot comments are only implemented for tasks.

**Comment by dottorer** [comment]
If not too much effort, would be good to get it consistent. How much effort would it be?

**Comment by dottorer** [comment]
@phillipoertel looking great in app. 

1. It seems to not detect changes to location or task organizer.
2. When changing task organizer can we email the old and the new organizer?

**Comment by dottorer** [comment]
3. Changing things like tipos might be too chatty when send emails to everyone. Could we have a clean and friendly message "You have changed xxx, yyy and zzz. Do you want to notify the interested helpers about this change?" And only the send out email? Let me know what you think @phillipoertel

**Comment by dottorer** [comment]
@phillipoertel Tested mail merge variable, upgrade EN, DE and FR mailchimp templates. Looks good.

**Comment by phillipoertel** [comment]
@dottorer we could place a checkbox "send notifications" next to the save button on the task form, checked by default. That would be a technically simple, non-intrusive way to solve the problem. If we do the modal, it will require two clicks on _every_ save.

**Comment by phillipoertel** [comment]
I'm happy to add the sweet alert gem though, we'll need it in other places anyways.

**Comment by phillipoertel** [comment]
Third option: have two buttons for saving (comparable to the Github commenting buttons):
[Save] [Save (without sending notifications)]

**Comment by dottorer** [comment]
the checkbox is a good solution...let's go with that for now. But I think we need to differentiate it from the rest of the update field by thin line or something as it is only guidance field, not a stored value.

And of course we want the sweet alert ;-)

**Comment by phillipoertel** [comment]
What's left to do:

* also create a comment when the location or organizer changes; currently changes there aren't picked up
* @dottorer has decided on the "two buttons" solution for update notifications; i.e. have one button with [Save] and the other [Save and notify] below the task. This still needs to be implemented.

**Comment by phillipoertel** [comment]
Tracking changes on location, organizers (and volunteers) is implemented and on staging. 
Will implement the "two buttons" solution next (tomorrow).

**Comment by phillipoertel** [comment]
@dottorer "two buttons" solution is done, completing this story. Testable on staging!
Let me know if you would like to colorize the buttons differently.

**Comment by dottorer** [comment]
@phillipoertel tested in STG - working well.

Styling of button we can consider with the new layout of the task with the sourcing options...
