### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by phil-monroe** [lale-help/lale-help#25]

**Comment by dottorer** [comment]
Hi @phil-monroe  is this different than #15 ? We should close on if duplicate and track our efforts for comment stream on a task in one issue.

**Comment by phil-monroe** [comment]
At the time, no. Discussions were thought of as a separate thing from task comments that would be used to discuss what tasks needed to be completed. That being said, based off the MVP we have discussed, this is no longer relevant.
