### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by phil-monroe** [lale-help/lale-help#26]

**Comment by phil-monroe** [comment]
@stephanerangaya / @madkap / @jamesfan

FYI: I just made a dedicated controller for dealing with stylesheets to try and keep things a bit more separated.

**Comment by madkap** [comment]
@phil-monroe got it. thanks

**Comment by stephanerangaya** [comment]
Great! The guideline is still in sketch format (updated some of the screen and optimized for smaller displays) and I'll work on changing the styles in the stylesheet this week.

**Comment by dottorer** [comment]
I think we have a workable style guide to move the app forward for now...
