### ISSUE TITLE
README + Dev Setup + License 

### ISSUE THREAD

**Issue by phil-monroe** [lale-help/lale-help#27]

**Comment by dottorer** [comment]
I think we can close this out with what we have for there right now. Only thing is that we are missing the MIT open source license file.

@phil-monroe did you already add this somewhere and do you know which format this needs to have to be 'official'?

**Comment by dottorer** [comment]
Is it as simple as droping a license.md file into the repo? 
http://programmers.stackexchange.com/questions/157968/how-to-manage-a-copyright-notice-in-an-open-source-project

**Comment by dottorer** [comment]
MIT license in root folder now . Done!
