### ISSUE TITLE
Date / timeframe for tasks

### ISSUE THREAD

**Issue by phil-monroe** [lale-help/lale-help#28]

**Comment by dottorer** [comment]
We should work towards the definition in: https://docs.google.com/document/d/1zMsfpX7IrjGhm4_Ee2Ry_LZIC2uu-MsgXzYm-DsT0B8/edit# 

 - specific date / time (for point in time tasks)
OR
 - due by (for due date tasks)

Also, we should allow to specify estimated # of hours required to complete the task so helpers can see when they best have the time to do it.

**Comment by tmandke** [comment]
Doc looks good. but I am assuming this issue is to setup
* specific date / time (for point in time tasks) OR
* due by (for due date tasks)
 
And 
* estimated # of hours required

I am going to set it up assuming as such

**Comment by tmandke** [comment]
@jamesfan @stephanerangaya Can you provide the UX for either just the above 3 thing added or a more complete one with more of the things in @dottorer 's doc

**Comment by dottorer** [comment]
@tmandke - you got it exactly right on the spec. I tried to clarify the various time / period options more in the doc.

It basically comes down to 3 options on how a task could be scheduled. We could initially go with a simple radio button to choose on of the three and then have 

Task needs to be done exactly on: **bold**‘Friday, Sept 19th’**bold** at **bold**‘3 p.m.’**bold**

Task needs to be done on: **bold**‘Friday, Sept 19th’**bold** in the period **bold**‘3 p.m. - 5 p.m.’**bold**

Task needs to be done anytime before : **bold**‘Friday, Sept 19th’**bold**

The items in bold would be date pickers or time drop down controls. And we still need to specify the estimated time commitment so volunteers can plan their availability.

**Comment by dottorer** [comment]
@jamesfan But maybe James has a better idea on how to build a UX for this. I do like the simple way task rabbit does this (see doc) but this might be too much work to accomplish initially.

And to course, dates / times would need to follow locale settings for the format and language for the names of months, etc.

**Comment by dottorer** [comment]
We can specify various due date options in staging right now, so we can close this. however, we need to improve on the UX for the date picker as it is not intuitive yet. Will open separate issue for that.
