### ISSUE TITLE
Workgroup must have at least one organizer

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#280]
When we refactored the work group organizer from a drop down to the explicit 'add organizer' function, we lost the validation that a new workgroup needs at least 1 organizer and that we cannot delete the last organizer either. We need to fix that up again.

**Comment by dottorer** [comment]
@phil-monroe i don't think @phillipoertel can still take a look at this in his current sprint at Lale. Could you check this out and see what's missing? Possibly once clear Kristy could help out...

**Comment by NolanChan** [comment]
To my understanding, each working group starts off with 0 organizers. I assume that this validation would only go into affect when an organizer is added?

**Comment by dottorer** [comment]
@NolanChan Discussed with @phil-monroe and we said that we should make the creator of the work group its first organiser upon creation. Then we need to validate that they cannot delete the last organizer row. Makes sense?

**Comment by NolanChan** [comment]
Just to clarify the last part "we need to validate that they cannot delete the last organizer row" you mean that every work group must have *at least 1* organizer?

**Comment by dottorer** [comment]
Exactly!

**Comment by phillipoertel** [comment]
Add organizer field to create a work group form; initially blank, but one circle member must be chosen.

**Comment by phillipoertel** [comment]
Ticket is implemented and testable on staging!

**Comment by dottorer** [comment]
@phillipoertel  tested in STG - works perfectly...
