### ISSUE TITLE
Add icons to dashboard title view for circle, workgroup and project

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#287]
We now have 3 main entities that have a dashboard overview. When navigating around it is easy to lose context which object type is being viewed right now. Therefore we should add an icon representation before the title.

**1. Circle**
Use https://useiconic.com/icons/target/ 
![image](https://cloud.githubusercontent.com/assets/14217285/14424884/d9cccec4-ffe3-11e5-9a12-84fde17e0d34.png)

**2. Workgroup** 
Use existing icon
![image](https://cloud.githubusercontent.com/assets/14217285/14424894/f131adc8-ffe3-11e5-9769-7eaafc3df91d.png)

**3. Project**
Use existing icon (or come up with better one like https://useiconic.com/icons/project/)
![image](https://cloud.githubusercontent.com/assets/14217285/14424920/1e462d5c-ffe4-11e5-8d29-de70f6fe0b9d.png)

**Comment by NolanChan** [comment]
Do we need to purchase the icons on https://useiconic.com ?

**Comment by dottorer** [comment]
We should stay free and open. The is OpenIconic which we should already have bundled in the repo...but any other suitable ickn would work as well, just needs tobe crisp abd scalable.

**Comment by NolanChan** [comment]
Just to confirm the issue, currently none of the entities have picture representations in their main title (and so we need to add them); however when they show up in other subtitles, they have pictures?

<img width="1183" alt="screen shot 2016-04-11 at 4 10 05 pm" src="https://cloud.githubusercontent.com/assets/1487616/14445180/e07eb0fe-ffff-11e5-8804-7abb4882e3b2.png">

**Comment by dottorer** [comment]
You got it. We are missing the iconic representation in the title of the 3 flavors of dashboard pages.

**Comment by NolanChan** [comment]
Got it, I'll work on it soon

**Comment by dottorer** [comment]
@phillipoertel added new icons into the lale font yesterday which we can use for all the above cases:

![image](https://cloud.githubusercontent.com/assets/14217285/14975334/f58b2a10-1100-11e6-89f3-d1cbf8b2871f.png)

![image](https://cloud.githubusercontent.com/assets/14217285/14975351/13ee04fa-1101-11e6-8c5a-40a7ee6ad0a0.png)

**Comment by dottorer** [comment]
Looking great! We might add a tiny bit more space underneath the icon + heading and the descr field...
