### ISSUE TITLE
Projects of multiple tasks

### ISSUE THREAD

**Issue by phil-monroe** [lale-help/lale-help#29]

**Comment by dottorer** [comment]
Changing title to reflect what we are implementing here per mvp1 spec document.

**Comment by dottorer** [comment]
This has been discussed with the circle admin of the the helper group in Taufkirchen. It is a very useful real life feature to aggregate several tasks into a project and provide stats view of the whole projects as outlined here: https://docs.google.com/document/d/1jEzrh9tTZ1nHFbQDxGUjk3_0g_6HXfMt2pqb5TzxTbo/edit#heading=h.cqb5iqe6x84l 

"project_stats: we need to provide visibility into execution progress on the project level such as  “total included tasks = 23, tasks completed = 11, total helpers needed = 45, current helpers assigned = 34"

**Comment by dottorer** [comment]
@phillipoertel Updated specs in link above to reflect current design and required work. We can discuss on your next sprint if this level of detail is sufficient for the specification.

**Comment by dottorer** [comment]
Closing as we track all other items in #297 .
