### ISSUE TITLE
Last nits for feature 'projects'

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#292]
- [x] 1. some labels on create and edit supply form not translatable: location, working group, organizer, project

- [x] 2. after saving a new task or supply, using the back button takes you back into edit mode, not into the project homepage.

- [x] 3. as in #286 listed, the 'copy task' button should be available on tasks that the user can normally edit. We should use the same logic.

- [x] 4. Copy task saves a new task even before the orange button is pressed. So if i hit copy, but then navigate away i seem to have an instance hanging out there.

- [x] 5. German translation for copy task missing "translation missing: de.circle.projects.clone.new_task_name". (Ralf to look and add)

- [x] 6. buttons New Task / Supply inside projects should only be visible to project organizer, work group organizer of this project, or admin. Right it shows to all.

**Comment by dottorer** [comment]
@phil-monroe Hi Phil, i am collecting last nits that i found during testing. Maybe we can straighten those before we push to Prod...thank you!

**Comment by dottorer** [comment]
@phillipoertel FYI, listing last items here before releasing Projects.

**Comment by phil-monroe** [comment]
should be just the translations left @dottorer

**Comment by dottorer** [comment]
Translations done and merged. Ready to bring in then?

**Comment by dottorer** [comment]
All done and merged - looks good!
