### ISSUE TITLE
Create Task ignores selected work group

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#296]
When creating a new task, the work group selected is ignored and the first work group of the list is picked:

I creating the task, I selected work group 'Sprache und Bildung' but what got saved is 'Arbeit'

![image](https://cloud.githubusercontent.com/assets/14217285/14616973/af544f9a-05ac-11e6-9768-7e79d8809b07.png)

**Comment by dottorer** [comment]
@phil-monroe This is a pretty critical bug especially since we now do no longer allow changing the work group after the fact. It means all new tasks are in the first work group alphabetically!

**Comment by NolanChan** [comment]
The problem is here: https://github.com/lale-help/lale-help/blob/master/app/mutations/task/base_form.rb#L2

Currently trying to figure out how to actually assign the working group

**Comment by dottorer** [comment]
@NolanChan great work finding the mistaken line - way to help us out! Looks like the .first would do it. This bug was introduced in a recent code change so we should be able to find it quickly and ensure that we save what is being selected in the form. @phillipoertel is trying to look into it soon as well.

**Comment by phillipoertel** [comment]
@dottorer I just pushed a bugfix to master. From a brief check it worked correctly on adding new tasks from within and outside of a project. Please review and merge yourself if you are satisfied.

It's quick and hackish and only adds more complexity to the current task and supply create and update code, though. That code would really be easier to maintain/develop after some refactoring/simplification and some unit test coverage.

**Comment by phillipoertel** [comment]
I added quite a lot of complexity myself btw., with the projects and date picker features.

**Comment by NolanChan** [comment]
Haha I was looking all night but I couldn't really understand where the problem was coming from. It seemed that though the `outcome` had the right `working_group`, it would just auto-magically revert back to the first available working group.

**Comment by phillipoertel** [comment]
@dottorer please ignore the part about merging in my comment above ...

**Comment by dottorer** [comment]
@phillipoertel Hackish fix seems to work in STG, ready to push to PROD then. As for the refactor,  this sounds like a core area to get right and robust, so could you open an issue outlined the work and giving a rough effort estimate? Thanks!

**Comment by phil-monroe** [comment]
Hey gang, thanks for working on this and sorry for the radio silence over the past couple of days. I made a couple changes that should hopefully put this to bed in a non-hackish way for both tasks and supplies.
