### ISSUE TITLE
Project stats in project dashboard

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#297]
Completing the feature from #29, we need to add project stats to the dash board 'info' tab as follows:

![image](https://cloud.githubusercontent.com/assets/14217285/14632190/a641559a-0617-11e6-8c80-22d6e2712041.png)

This should show quickly how many tasks and supplies are still to be sourced and how many helpers we still need.

A. Tasks = all tasks included in the project, broken down by status
B. Supplies = all supplies included in the project, broken down by status 
C. Helpers = all required number of helper from all tasks (not supplies) in project

**Comment by dottorer** [comment]
For completion during the next stint...let me know if you have any questions on the data sources or design.

**Comment by Matthias-Lale** [comment]
Bei Helfer könnte man auch eine Dreier Teilung machen : "urgent needed", "needed" and "asigned"

Alle Stati sollten mit Link versehen sein, so dass man auf die entsprechende Overview kommt. 

Viele Grüße 

Matze 



Viele Grüße 

Matthias Walz

**Comment by phillipoertel** [comment]
@dottorer I'm done IMHO; also added the correct icon for supplies and fixed the urgent tasks count. Please review on staging.

I also updated these icons:
- "Help provided" and "Circles" on the member profile page
- location everywhere
- project on the task/supply page

**Comment by dottorer** [comment]
Looks great!
