### ISSUE TITLE
Lale-bot to insert comments on task status changes

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#298]
It is important to see how tasks and supplies change status over time. After some design discussions, we decided to introduce the 'Lale-bot'. With this function, we will insert comments into the comment thread which looks like this:

![image](https://cloud.githubusercontent.com/assets/14217285/14632472/2c358fee-0619-11e6-8d56-f9551d3fe5c8.png)

We will use this for the following changes with the following text:

1. User assignment: "xxxxx signed up for this task on DATETIME."  (xx = user affecting change)
2. User un-assignment: "xxxxx unassigned this task on DATETIME."
3. Task completion: "xxxx completed this task on DATETIME."
4. Task re-open: "xxxxx re-opened this task on DATETIME."
5. Task copied: "This task was copied from task yyyyy on DATETIME." (yyy = name and link to source task)
6. Task invitation: "xxxx invited yy helpers to this task on DATETIME." (X = sender of email, y = number of targeted participants)
7. Task data changes: For any field value changes we will implement the design from #249.

The hover over text should always say 'Lale' as commenter and have the datetime of when comment was made.

**Comment by dottorer** [comment]
We will need a nice function that handles the comment inserts and a clean way of adding these text / variable blocks, including full i18n of text and dates.

**Comment by dottorer** [comment]
adding as candidate for @kristysnet to look at.

**Comment by dottorer** [comment]
[Stellenbeschreibung Marisol.pdf](https://github.com/lale-help/lale-help/files/244237/Stellenbeschreibung.Marisol.pdf)

**Comment by dottorer** [comment]
@kristysnet Hi Kristy, first cut at this is looking awesome! Here a few nits to round it out:

![image](https://cloud.githubusercontent.com/assets/14217285/15068004/a32f5216-1374-11e6-9ae1-cc58149f69b0.png)

1. Lale-bot should have the default user picture of our Logo in grey: 
![laleiconreversed60](https://cloud.githubusercontent.com/assets/14217285/15068034/cfb221ba-1374-11e6-9125-186339a644c4.png)
 
2. To distinguish the bot comments from user comments, maybe we can style the box a bit differently:
2.1 use white background, not grey
2.2 show dotted line outline
![image](https://cloud.githubusercontent.com/assets/14217285/15068198/dde9ac8e-1375-11e6-9849-808df415037e.png)


What do you think - looking good?

**Comment by kristysnet** [comment]
@dottorer sounds good, i'll get those changes in soon. Also, I forgot to mention that this was merged into master but needs some translations: 
tasks.auto_comment.user_assigned
tasks.auto_comment.copied
tasks.auto_comment.completed
tasks.auto_comment.user_unassigned
tasks.auto_comment.reopened
tasks.auto_comment.invited

**Comment by dottorer** [comment]
Actually the DE trans is in akready, adding FR on Monday...

**Comment by phillipoertel** [comment]
@dottorer bot comments are currently saved to the db in the circle language, so they can't be shown in different languages. Would this be important?

**Comment by dottorer** [comment]
@phillipoertel Thats correct, Lalebot ever only speaks circle language.

**Comment by phillipoertel** [comment]
@dottorer times on the comments are currently two hours off in Germany, because they are stored in UTC in the DB and we haven't set a time zone on the Rails app.

Would you like to change that? I see two options:
1. set time zone to Europe/Berlin. That way they would be correct in most of Europe, but wrong everywhere else
2. render the times client side, getting the correct time zone from the browser/user's OS. That should work correctly most of the time, but may require some fiddling, although there's this gem that should help: https://github.com/basecamp/local_time

**Comment by dottorer** [comment]
@phillipoertel i am used to solution 2 but also well aware of the complexities surrounding time zone. We would need to ensure that reminders are triggered at the correct time etc. (always 8am for the day to come).

I think the quickest might be for now ti focus on CET but kets briefly discuss the gem for option 2 today.

**Comment by dottorer** [comment]
This is all complete - working nicely! Thank you!
