### ISSUE TITLE
I18N

### ISSUE THREAD

**Issue by phil-monroe** [lale-help/lale-help#30]
Setup [I18N](http://guides.rubyonrails.org/i18n.html#the-public-i18n-api) in the application

#### Setup
- [x] Basic Setup (#36)
- [ ] CSS
- [ ] Constant Iteration

#### Translations
- [ ] German: @dottorer
- [ ] French: @stephanerangaya 

Tips: 
- https://robots.thoughtbot.com/foolproof-i18n-setup-in-rails
- http://www.lauradhamilton.com/internationalization-for-ruby-on-rails-apps

**Comment by dottorer** [comment]
I think this is mainly done now. Longer term a better support for translations would be welcome but we can manually update strings for now...closing.
