### ISSUE TITLE
Ability to de-activate work group

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#302]
We need to provide the ability to deactivate a work group. This should be done from the admin / work groups tab.

- We need to have 2 listing of work groups
 - Active work groups: as is, but shows button 'Edit' / 'Deactivate'
 - Inactive work groups: shows list of inactive WGs, shows buttons 'Reactivate' / 'Delete'

![image](https://cloud.githubusercontent.com/assets/14217285/14671419/05bb04f0-06f2-11e6-9f43-14ce41f86760.png)

Rules:
- Only work groups with no open tasks / supplies can be deactivated ('deactivate' button should appear for all WGs in grid, but message should say "You need to complete all tasks / supplies before deactivating group".
- if group is deactivated it is no longer shown in left nav.
- if group is deactivated it is no longer shown in any prompts on tasks or supplies or projects.

**Comment by dottorer** [comment]
Adding for Phillip as next sprint work candidate.

**Comment by phillipoertel** [comment]
What's left to do:

* columns of the tables need to be aligned properly
* only allow blocking a working group when no incomplete tasks and supplies remain (show a warning message instead, similar to blocking a user)

**Comment by phillipoertel** [comment]
@dottorer I'll finish this one now.

**Comment by phillipoertel** [comment]
@dottorer Done and testable on staging!

**Comment by dottorer** [comment]
@phillipoertel Tested in STG - works perfectly - awesome!!!

**Comment by dottorer** [comment]
@phillipoertel Related nit: could we move the 'create new WG' button into the section for active groups and style it as follows: 
![image](https://cloud.githubusercontent.com/assets/14217285/16009501/4056807a-317d-11e6-8ace-018a22bbad82.png)
