### ISSUE TITLE
Add comments function to user profile

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#317]
Admins often want to track comment about helpers. We need to offer the comment function on a user per circle. Only admin can add or see comments. We can also show the Lale bot comments from #309 there.

**Comment by dottorer** [comment]
@kristysnet @phil-monroe Guys this will likely require some larger refactoring from Taskable over to its own more broadly used Commentable or something. Can you take a look and see what this would entail? Is it massive work or doable?

**Comment by phillipoertel** [comment]
@kristysnet @dottorer I merged the PR, but the task_id and task_type fields should be removed after this feature was deployed to production successfully, as they will then be unused (and confusing to future maintainers of lale).

**Comment by dottorer** [comment]
Looking great
