### ISSUE TITLE
Lale Bot mixes languages on Task changes: “Ralf changed Anzahl ...“

### ISSUE THREAD

**Issue by phillipoertel** [lale-help/lale-help#325]
as mentioned by @dottorer via email:

---

Hmmm, Lalebot should only and consistently speak in the language of the circle. Seems like the field label is in German, but the sentence is not. 

@Phillip, can we verify this?

---

**Comment by phillipoertel** [comment]
@dottorer fixed and testable on staging.

**Comment by phillipoertel** [comment]
![bildschirmfoto 2016-05-13 um 11 33 41](https://cloud.githubusercontent.com/assets/5188/15243868/927bff34-18fe-11e6-83d5-faa6146fb640.png)

This is what the text looks like in German now. If you take offense at the grammar (missing article), I could change the German translation for tasks.auto_comment.updated to "%{user} hat folgende Felder geändert: %{changed_fields}".

**Comment by dottorer** [comment]
LGTM
