### ISSUE TITLE
Location is not copied when using 'copy task'

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#327]
We always use the default location of the circle. It should carry forward the source task location.

**Comment by dottorer** [comment]
@phillipoertel now that we have track changes on location, does this come essy to do?

**Comment by phillipoertel** [comment]
Its easy anyhow; I'll fix it this session. 

Von unterwegs gesendet, deswegen kurz und evtl. mit Tippfehlern

**Comment by phillipoertel** [comment]
@dottorer Not as easy as I thought, but still fixed and testable on staging :-)

**Comment by dottorer** [comment]
@phillipoertel Tested in STG - LGTM!
