### ISSUE TITLE
Nit: Lalebot comments should not be counted in task list view

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#332]
![image](https://cloud.githubusercontent.com/assets/14217285/15266808/9ec17c76-19b0-11e6-8846-a2e1997963f3.png)

Only real user comments should be tracked as commentary in the task listing view. This is intended to show how much people go back and forth on a task, not how much the Lale bot chats...

**Comment by NolanChan** [comment]
Hi @dottorer I think I can look into this one. Also is there a list of issues that need to be done sorted by necessity?

**Comment by dottorer** [comment]
@NolanChan Thanks for looking into it. I usually label the issues that could use some help with 'help wanted' so they can be identified. I will go through the list and check that they are correctly applied.
