### ISSUE TITLE
Leftnav improvements

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#339]
Users have reported issues in understanding our leftnav organization. I am proposing a revision of that as outlined in:
https://docs.google.com/document/d/1JcJGup4qTUIyPdqLZTJ8AMLjHJm_jPhX9RBaKMpWnec/edit

**Comment by dottorer** [comment]
TODO LIST for us to check off items as this work in completed:

Leftnav:
- [ ] add a ‘Homepage’ link here
- [ ] segment header for ‘Overviews’
- [ ] Helper List is a link to a page with 2 tabs: “All Helpers” and “Organizers”

Circle homepage:

- [ ] add description to circle definition and display on dashboard (similar to working groups)
- [ ] use tabbed page layout for Tasks, Supplies and Projects.
- [ ] show circle level stats of (as we do on projects today):
-- [ ] number of helpers in circle
-- [ ] Tasks (open / urgent / completed)
-- [ ] Supplies (open / urgent / completed)
- [ ] remove circle leaders and organizers
- [ ] move 'Contact admin' into footer area on right.

My Calendar:

- [ ] Tabbed view for things I am volunteering and things I organize.
- [ ] Sections for tasks and Supplies in each category.

Completed tasks:

- [ ] Show link ‘Show completed tasks…’ that toggles the task list to only show completed tasks in this work group
- [ ] In tabbed header, show number of open tasks (like in leftnav already). Not needed to show count for completed tasks.
- [ ] Repeat these 2 functions for supplies as well.

**Comment by dottorer** [comment]
@kristysnet the leftnav looks great and is done (with #236 still WIP). I think it is a great improvement!

I had another request which I think is helpful. Could we move the 'Add' button into the leftnav and make the drop down menu unfold on the right?

![image](https://cloud.githubusercontent.com/assets/14217285/16005437/922b8d8e-3167-11e6-8b3f-a161160946bb.png)

If that's feasible, I would really like to try it.

One other note: on stg, the new circle homepage renders quite slowly fir the circle 3. Looks like with some data it gets slow. Is there anything we see taking time to render?

**Comment by dottorer** [comment]
Hi @kristysnet Phillip and I are preparing for PROD push on Thursday so we have a chance to respond to issues on Friday while I still have him on deck. Let me know if this button reshuffle could still fit in...

**Comment by kristysnet** [comment]
@dottorer I put up a PR for the button moving: feature/move_add_button #361
I haven't looked at it in anything except chrome yet. I should be able to look at it in other browsers later this afternoon. If you could take a look at it in mobile, that would be helpful.

**Comment by dottorer** [comment]
Looked at it in the rev app - nice. Some styling:

* center it in the area (gives bit more space underneath it), 
* orange outline for the drop out, 
* little sliver of space between drop out and the button
* maybe tiny drop shadow...

**Comment by dottorer** [comment]
For reference, somewhat like this, just to the right of it. We might also replace the (+) icon with a small arrow pointing to the right.

![image](https://cloud.githubusercontent.com/assets/14217285/16088109/de32b9fe-3325-11e6-8e34-45e6a2e330ae.png)

bit spacing between the drop menu, light shadow, etc...

**Comment by dottorer** [comment]
Looking very good now!

@kristysnet Sincde @phillipoertel was working on centralizing the 'edit' actions on our primary objects into a button, we united the styling based on yours and merged it all together. All further work should be off the final version on master.
