### ISSUE TITLE
lale.help platform homepage

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#34]
We need a root homepage for the platform itself. This page is where we land on at www.lale.help.

It needs to be informational to non-registered users, allow sign up for a circle or new circle creation. It also needs to provide background on the lale non-profit and our mission.

Design spec for such a heom page is here: 
https://docs.google.com/document/d/1SxMJPjNfpGbUw9aQ9SVZ-C3E1T3ZQXtB1C0MsNWqCxk/edit#

**Comment by phil-monroe** [comment]
@dottorer: do you think this is required for the MVP? We were hoping to focus on getting the app usable for the people that will work in it most often. Once we have that, we can nail down the "i want to help right now!" use case. Do you think that makes sense?

**Comment by dottorer** [comment]
I think we can work this somewhat in parallel. I need a form of simple website to respond to www.lale.help and we can wire in the app login there initially. But many folks are pinging me and are confused because they get an empty spot. Also, i hope that i can find a web page Guru and it is mostly static content and styling. Lets chat today briefly....

**Comment by dottorer** [comment]
I think we can close this for now as we have a basic website in place. We will open issues for an expansion and rebrand soon...
