### ISSUE TITLE
Do not show task that are part of projects in circle / workgroup task list

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#342]
Projects tend to include many tasks, but they are mostly confusing out of context of the project. We should therefore not show them on the main task list on the circle or work group. Each of these views have a tabbed homepage that also list projects and therefore in-project tasks can be found there.

**Comment by phillipoertel** [comment]
Thanks to Rails scopes I could implement this in 15 minutes; testable on staging.

**Comment by dottorer** [comment]
Done and LGTM!
