### ISSUE TITLE
Remove 'register' link from PROD landing page

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#344]
The current start page app.lale.help offers the 'register' option which then also allows the creation of a brand new circle. This is not a supported flow yet, so we need to suppress it (in PROD, this is ok in DEV).

![image](https://cloud.githubusercontent.com/assets/14217285/15821743/0d710e0e-2bf2-11e6-83ca-6bf027b99387.png)

Instead we should say "Don't have an account? **Contact us** to create a new circle for you." where the 'Contact us' is linking to an email to "mailto:info@lale.help".

**Comment by dottorer** [comment]
This change is necessary since we are going to include the link to 'app.lale.help' as part of the top nav from Lale.help main website.

**Comment by phillipoertel** [comment]
Implemented, but not testable on staging since it is (per spec) only visible on production (and development environments).

**Comment by dottorer** [comment]
@phillipoertel thinking this through, I might need to add a way in PROD to create a brand new circle for new signed up groups. Seems like I locked myself out of this option :-)

**Comment by dottorer** [comment]
Works like a charm in PROD!

**Comment by dottorer** [comment]
@phillipoertel Need to re-open since we need to find a way for us as platform operators to create a new circle instance for new customers. I am not sure I can get onto the active admin console. 

Let's discuss today...I have a pending request for a PROD circle :-)

**Comment by phillipoertel** [comment]
@dottorer after logging in you should have a link to "Lale Admin" in the top right user dropdown menu. That would be one way of creating a circle, but it would require some adaptations in the admin.
alternatively we could just show the previous create "new circle" link to lale admin users. that would probably be faster, but you'd always end up in the circle as well, I guess.

**Comment by dottorer** [comment]
In prod, we can use https://app.lale.help/register to get to the page to enter a new user and create a new circle.
