### ISSUE TITLE
Centralize primary actions on objects into drop down menu 

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#349]
We have quite a few action buttons to change state of our core objects like tasks and working groups. This leads to user confusion and real estate clutter. We should clean it up as follows:

**TASKS**

Offer one central button for 'Edit' on each object which then unfolds a drop down menu with option:
![image](https://cloud.githubusercontent.com/assets/14217285/15964684/021b8540-2f1a-11e6-9039-24dcf82ec48e.png)

![image](https://cloud.githubusercontent.com/assets/14217285/15964694/0c0d8012-2f1a-11e6-94ae-5d62b7beff11.png)

"Edit task"
- Change task
- Mark task complete
- Copy task
- Delete task

This also moves the 'delete task' button from the edit screen to this menu. The remaining options on edit are 'Save', 'Save and notify' and the link-styled 'cancel'.

**Comment by dottorer** [comment]
**SUPPLIES**

Analogous to tasks, this is how supplies look:
![image](https://cloud.githubusercontent.com/assets/14217285/15965016/bf30ab3c-2f1b-11e6-8df5-0fc7011524f4.png)

![image](https://cloud.githubusercontent.com/assets/14217285/15965020/c8985058-2f1b-11e6-86ec-0417babc22b2.png)

**Comment by dottorer** [comment]
**WORKING GROUPS**

Due to the more complex process flow, the main create - deactivate - delete options will remain only available to the admin in the admin console:

![image](https://cloud.githubusercontent.com/assets/14217285/15965209/ca8d9c46-2f1c-11e6-8aa4-8e8030a24c7a.png)

Therefore the working group has only the 'Edit' option:

![image](https://cloud.githubusercontent.com/assets/14217285/15965245/f59152de-2f1c-11e6-9061-a5b924c26448.png)

The 'Join' action for helpers needs to be displayed in or near the helper box.

The edit form only offer save / cancel

![image](https://cloud.githubusercontent.com/assets/14217285/15965268/16dccbe4-2f1d-11e6-8509-d2d7144695ad.png)

**Comment by dottorer** [comment]
**PROJECTS**

Here we only have the 'invite by email' option on the project level and should include it directly on the page:

![image](https://cloud.githubusercontent.com/assets/14217285/15965494/81bdbb34-2f1e-11e6-9235-4d9014868f59.png)

Edit takes you directly to the edit screen with 2 buttons:

![image](https://cloud.githubusercontent.com/assets/14217285/15965511/aed015e0-2f1e-11e6-924e-eff24e49bbb9.png)

**Comment by phillipoertel** [comment]
- on working group: add button to join.
- on project: add "Find helpers" button with modal (invite options only in modal)

**Comment by phillipoertel** [comment]
@dottorer except for the project invite options everything should be implemented & testable on the review app. I'm also interested if you are OK with the layout consolidations of the circle, working group and project dashboards -- they now look almost the same since I unified the CSS. You could already have a look and give me feedback when you find the time.

**Comment by phillipoertel** [comment]
Review app: https://lale-help-stg-pr-362.herokuapp.com/

**Comment by dottorer** [comment]
Done and deployed - looks awesome! Thanks you!!!
