### ISSUE TITLE
Re-order comments section

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#354]
We should re-order the layout of the comments section as follows:
![image](https://cloud.githubusercontent.com/assets/14217285/16009547/7cdb8036-317d-11e6-8cff-464c4fbc1970.png)

- style frame around the whole section
- Move the entry field 1st, 'post' button under it
- show newest 5 comments sorted by post date desc.
- show 'show all comments' option underneath.

**Comment by phillipoertel** [comment]
@dottorer this can be reviewed on staging as well.

**Comment by dottorer** [comment]
LGTM - nicely done!
