### ISSUE TITLE
For inactive working groups, the organizer role is also inactive

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#363]
When a helper is organizer of an inactive group, the 'Add' button is still shown and causes the add action to fail. We need to not show the 'Add' button to users unless they are the organizer of an active work group.

**Comment by phillipoertel** [comment]
@dottorer I guess you mean the "Add" button for tasks/supplies/projects. Indeed, when there are only inactive WGs for a user, it should not be displayed; as if there weren't any WGs at all.

So it would be shown if:
- for circle admins: circle has at least one active active working group
- for "regular" users: user is admin of at least one active working group

**Comment by dottorer** [comment]
@phillipoertel yes your two outlined criteria for the button are perfect.

**Comment by phillipoertel** [comment]
@dottorer Implemented and testable on staging!

**Comment by dottorer** [comment]
@phillipoertel Trying to verify the fix, I noticed the following. In staging, the user 'ralf.schroeder@gmail.com' is still organizer of group 'Sprache und Bildung' but already does not have access to the 'Add' button. This group is active so I expect him to have it. Can we look why?

**Comment by dottorer** [comment]
@phillipoertel Can you quickly check the scenario above to see why the 'add' button is not showing for that user?

**Comment by phillipoertel** [comment]
@dottorer implemented and on staging, please review.

**Comment by dottorer** [comment]
@phillipoertel Tested on case above - works perfectly now....
