### ISSUE TITLE
Add google analytics tracking ID to app.lale.help

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#365]
The analytics ID is UA-69286385-2, the snippet is:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69286385-2', 'auto');
  // anonymize the IP; see https://goo.gl/EDPmwo
  ga('set', 'anonymizeIp', true);
  ga('send', 'pageview');

</script>


```

**Comment by phillipoertel** [comment]
Tracking is set up for staging and production. Still missing though: a separate Id for staging, so we can test integration correctly before going live. For now I write a log message to the browser's console whenever a new pageview gets submitted to GA so we can test; this can be removed later.
For further insight, the Chrome extension "GA Debug" may be useful: https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna

**Comment by dottorer** [comment]
@phillipoertel Added separate tracking ID for staging in #377 . Both sites have referral exclusion setup mutually so we should get clean hits.

**Comment by phillipoertel** [comment]
@dottorer does this work as expected on staging & production?

**Comment by dottorer** [comment]
Seems to work well...thanks!
