### ISSUE TITLE
Assign helper function adds same helpers twice

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#366]
If I clicked instead of once several times on the button “Helfer eintragen” (user fault), first nothing happens, but after a few seconds all Helpers I assigned in the box appear as often as I have clicked on the button. For example I assigned 3 Helpers A,B, C and left mouse click (on pad)  the button 4 times, then it appears A,B, C, A,B, C, A,B, C, A,B, C, as helpers.

We can also asdign the same helper twice if he clicks the email link.

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/16169840/4d301590-353d-11e6-9163-f60268080685.png)
![image](https://cloud.githubusercontent.com/assets/14217285/16169841/4d51359a-353d-11e6-908d-e8bf697fadcd.png)

**Comment by phillipoertel** [comment]
Thanks for reporting, I'll have a look at it later today. 

Von unterwegs gesendet, deswegen kurz und evtl. mit Tippfehlern

**Comment by phillipoertel** [comment]
I fixed this by disabling the button after the first click, then updated staging and production. 
I want to investigate at a later point why multiassign is possible, however. The backend should prevent this with the following line: https://github.com/lale-help/lale-help/blob/master/app/mutations/task/assign.rb#L12.

**Comment by dottorer** [comment]
I tested this solution and it works well with the button turning grey and showing the label that it is actively doing something. Also, I verified that you in fact CANNOT add yourself again by using the email link. This was always the case since users could have clicked on the same email button 5 times. It is strange that this is even possible through the UI though...
