### ISSUE TITLE
Error trying to create first WG for new circle

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#367]
When creating a new circle, I am trying to setup an initial working group. I get the following error:

https://rollbar.com/lale-help-stg/lale-help-stg/items/121/ 

This is halting me for a demo setup right now, could we take a look and see if I can overcome it somehow?

**Comment by phillipoertel** [comment]
Just fixed the bug, pushed to master and deployed to staging. Please deploy master to production via the heroku dashboard if you are happy with it, or let me know when I should do it.

**Comment by dottorer** [comment]
@phillipoertel tested in STG looking good. Could you deploy to PROD for me? Thank you for fixing it so promptly...
