### ISSUE TITLE
Pending users are shown in prompt for work group organizers.

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#372]
Pending users should NOT be able to be selected as WG organizers...

**Comment by NolanChan** [comment]
@dottorer I assume you mean "Pending users should **_not_** be able to be selected as WG organizers?

**Comment by dottorer** [comment]
@NolanChan Sorry! That's a terribly misguiding tipo - you are of course correct that they should not appear....

**Comment by phillipoertel** [comment]
Testable and deployed on staging.

**Comment by dottorer** [comment]
LGTM - Thanks @NolanChan for contributing a bug fix! :-)
