### ISSUE TITLE
Feature: provide banner ad space for sponsors of a circle

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#373]
The subscription fee for the Lale platform usage of a helper circle can be paid by a sponsor. As a result, sponsors can show their company logo inside the Lale platform as a banner ad.

See detailed specs here: https://docs.google.com/document/d/16z30iSQjoMWuf6_EoK_fFRrD3q-jsrD4CnKFDijqPm4/edit

###### Create Sponsor model
- [x] Name (required)
- [x] URL (optional?)
- [x] set up relations to circle
- [x] add description field (textarea)
- [x] Logo file (required. S3 upload)

###### Create Sponsorship model
- [x] circle id (required)
- [x] sponsor id (required)
- [x] starts_on date (required)
- [x] ends_on date (required)
- [x] add method to fetch currently active sponsorships
- [x] validate start date is before or equal to end date

###### Create Admin interface
- [x] to CRUD sponsors
- [x] to CRUD sponsorships
- [x] extend "new sponsor" admin action to allow image upload (image required)
- [x] extend "edit sponsor" admin action to allow image upload (image optional)

###### Display sponsorships on circle pages (sidebar)
- [x] show/position sponsor logo at the bottom of the sidebar
- [x] link to sponsor URL if present, opening in new window
- [x] rotate the logo regularly if a circle has multiple sponsors: choose a random image once per uer session
- [x] bugfix: image container collapses on staging :-/
- [x] display the uploaded sponsor-logo as-is, don't assign a size in HTML/CSS
- [x] ensure navigation isn't obstructed on smaller resolutions or with many working groups
- [x] respond gracefully on mobile/lower resolutions. Possibly only show sponsor name then
- [x] fix cropping of "Add" menu (German)

###### Display sponsorships in non-circle pages

- [x] don't show a sponsor

###### Display sponsorships in circle admin
- [x] new tab "Sponsors" has a table of all current sponsors (name, starts_on, ends_on)

**Comment by phillipoertel** [comment]
Additional comments / requirements:
- make sure leftnav isn't obstructed (circles with many groups)
- check responsiveness / mobile
- if a circle has multiple sponsory, rotate logos per page request
- sponsorship period should be adjustable (start YYYY-MM-DD to end YYYY-MM-DD)

**Comment by phillipoertel** [comment]
Do sponsors get to leave an URL, i.e. do we link the logo to their page?

**Comment by dottorer** [comment]
@phillipoertel: we should store a URL for the sponsor and linkfrom the logo to it.

**Comment by phillipoertel** [comment]
@dottorer two questions on this

- I'm wondering about the intention behind storing the sponsor's full address. 
I'd only do a real join to the address table and the geocode stuff that if the sponsor should become an active part of the lale application, i.e. displayed on a map, etc. 
Otherwise, a simple address text field would give much more flexibility, maybe combined with a general-purpose "contact info" / "remarks" field. 
The relation to the "real" address model may also require more setup in active admin if it should be editable on the same page as the rest of the sponsor info.

- if a circle has more than one sponsor, we discussed rotating the sponsor image on every page change (click). I now realized this would cause the logo to change and thus draw attention very often. To reduce distraction, how about rotating the logo once a minute, or once every n minutes instead?

**Comment by dottorer** [comment]
@phillipoertel 
ad 1) I don't think we need to store the full address in Lale as we will have to do this in some form of CRM system anyways as our paying customers. A simple address field should suffice, possible one that allows location on a map.
ad 2) so you mean rotating still only on server trips, but not on each trip but once every 3 minutes? Sounds good.
ad 3) URL is not required, but we should use it to link from the image if present.

**Comment by phillipoertel** [comment]
Created a pull request and review app: #381, https://lale-help-stg-pr-381.herokuapp.com

**Comment by dottorer** [comment]
@phillipoertel Couple of thoughts on the questions:

1. assign one (random) sponsor logo for the whole user session (i.e. until next login) -> I think having multiple sponsors will be possibly and edge case and we should go with the simplest solution for multiples. So your approach is a perfect start.
2. logo size OK? -> current logo size in review app seems a bit too big. Also, the dark background draws a lot of attention so we should tune down to #ECEFF1 
![image](https://cloud.githubusercontent.com/assets/14217285/16645232/cc8e484a-4422-11e6-9c55-944f9470c191.png)

3. The logo size is changing on mobile devices when switching from portrait to landscape. We should have this behave elegantly in size, too.

**Comment by phillipoertel** [comment]
Update on this story: still working on getting files uploaded & shown correctly with our custom image handling code. Almost done, I believe.

**Comment by phillipoertel** [comment]
Mühsam nährt sich das Eichhörnchen :-)

![bildschirmfoto 2016-07-08 um 16 36 44](https://cloud.githubusercontent.com/assets/5188/16690855/2f47335e-452a-11e6-8d62-f387b85d33a9.png)

**Comment by dottorer** [comment]
Geil - mit BMW als Gross-sponsor :-)

Geht es mit images jetzt schon?

**Comment by phillipoertel** [comment]
Ja, aber image upload geht bisher nur beim Neuanlegen eines Sponsors (nicht edit), ausserdem muss man sich einmal ein/ausloggen damit das Logo kommt; es ist auch serverseitig noch nicht skaliert (dh. die Datei ist noch sehr groß). Details siehe meine Liste oben.

**Comment by phillipoertel** [comment]
FYI: the currently visible sponsor is stored in the session, so changes in circle sponsorship only become visible on the next login.

**Comment by phillipoertel** [comment]
@dottorer I think this feature is done (and it's already deployed).

Let me know if the non-circle pages (/account; anything else?) should show any sponsor, right now they only show lale.

**Comment by dottorer** [comment]
@phillipoertel looking great. Just not sure why the heading in the tab of the circle admin view does not show german translation. Thought i pushed that yesterday, but might be a new separate string.
