### ISSUE TITLE
Once assigned, helpers cannot be removed by admin or orga

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#379]
In several scenarios, the helpers that were added using the 'Find Helpers' button, can no longer be removed as the little (x) icon does not show up...

**Comment by phillipoertel** [comment]
@dottorer I think this isn't a trivial issue; I already spent half a day looking into it. I believe class loading inside a Ruby gem (cells) is the issue.
A quick fix would be to make task/supply roles editable (and deletable) in the lale admin area, I believe that would be easy with the standard active admin tools.

**Comment by phillipoertel** [comment]
@dottorer I was able to fix this now and deployed it to staging / demo.

**Comment by dottorer** [comment]
Works for admin. Only small nit is that the (x) icon on the right overlaps the next helper tag in the assignee field, but good enough for now....
