### ISSUE TITLE
Out of memory errors: upgrade heroku-dyno for staging

### ISSUE THREAD

**Issue by phillipoertel** [lale-help/lale-help#383]
For some requests, we currently get the following error on staging:
 ```
2016-07-08T13:43:46.662384+00:00 heroku[web.1]: Process running mem=574M(112.2%)
2016-07-08T13:43:46.662384+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
```

Sometimes there's no response at all when we get the memory quota error, sometimes the HTML page still is served.

The quickest solution would be to to upgrade staging to a dyno with 1GB of memory. 

Interestingly, production is at only ~350MB memory usage, this should be looked into after the next production deploy.

**Comment by phillipoertel** [comment]
@dottorer could you look into this?

**Comment by dottorer** [comment]
@phillipoertel :+1: 
- PROD upgrade to dyno 2X (1GB ram)
- Staging remains at 512 (Hobby) for now until we see mem issues.
