### ISSUE TITLE
Do not allow users to click buttons too many times

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#385]
Currently users can click certain action / notification buttons multiple times and cause confusion by sending our emails too many times. Especially on 'Invite helpers' we had issues in production.

We should not allow users to click certain buttons twice and also provide improved guidance on what the system has done:

- disable button (can't be clicked again)
- set mouse cursor to spinning/loading
- style button as disabled
- ensure flash message is shown after the action

**List:**

- [x] In Find Helpers modal: "Assign helper" and "Invite helper"
- [x] On 'edit task' : Save and notify
- [ ] On 'edit supply' : We should also offer 'Save and notify' button here and make it clickable once.
- [ ] On Supply: We should introduce the 'Find helper' modal; otherwise we need to babyproof the 2 direct invite buttons.
- [x] On Projects: both 'invite buttons'

**Comment by phillipoertel** [comment]
@dottorer can you think of a generic message or string to display on the button when it is disabled? That would make translation easier and simplify the code, instead of requiring a custom message for each button. "Saving ...", "Updating ...", "..." aren't always ideal, however (for Invite circle, for example". I also thought about adding "..." to the button label, that could be a solution.

**Comment by dottorer** [comment]
@phillipoertel how would "Working on it..." / "Wird bearbeitet..." look for the generic cases? Important is to not make the button clickable twice, so it could just turn a notch darker or something visual as well. Label of course is also nice.

**Comment by phillipoertel** [comment]
@dottorer styling and clicking only once is no problem. If you're happy with that (i.e. not changing the label), I'm pretty much done.

**Comment by dottorer** [comment]
Ok, let's keep it at that for now. And we got the flash msg back, too?

**Comment by phillipoertel** [comment]
Fixed the buttons mentioned above. Note: I didn't add extra features ("Save and notify" button and the sourcing modal) for supplies, as I'm not sure about the priority. So it would be best addressed & prioritized in separate stories, or in a task/supply refactoring.

**Comment by dottorer** [comment]
Reviewed in DEMO. Works.
