### ISSUE TITLE
Close, reopen and delete projects

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#388]
Users are creating more and more projects to organize their efforts. But we have no way to close out a project. A simple form to do this would be to consider the project 'closed' when no single open task or supply are left to be done.

We then should list 'Closed' projects as a separate view just like we do for 'complete tasks'. Also, closed projects are not counted in any of the counters on badges.

**Comment by dottorer** [comment]
Also we need to offer 'Delete project' as an option in the drop down. It eill purge the project and all included tasks snd supplies, after an 'are you sure' check.

**Comment by phillipoertel** [comment]
So what needs to be implemented is:

#### 1. close project

Closing "automagically" may be confusing, and we'll have to handle the special case that a project was just created but has no tasks yet. How about having users close a project manually, by hand? That's the interaction they are used to from tasks and supplies.

#### 2. delete project

No comments sounds good. Since we'll have a "Super" Button now with the delete option anyhow, it would be easy to add the "close" option here as well.

**Comment by dottorer** [comment]
@phillipoertel 

1. Explicit closing is a good option. I was trying to keep it simple but manual is better. We will then need to offer re-open as well. Also we need to hide closed project from the list views of active projects and offer a nav link to switch to 'Closed projects...' (Like we do for tasks).

2. Delete project as a button option with a 'are you sure?' Check is perfect.

**Comment by phillipoertel** [comment]
Ok. Should be straight-forward to implement since we have most of the code & layout in other features already.
FYI I took the liberty to adjust the issue name to "Close, reopen and delete projects".

**Comment by phillipoertel** [comment]
Made good progress today. Remaining Todos:

- [ ] hide completed projects from lists
- [ ] request optical indicator for completed project
- [ ] align super dropdown menu
- [ ] add feature spec

**Comment by phillipoertel** [comment]
@dottorer will there be any indication that a project is closed on it's dashboard? For tasks and supplies the header changes color, but the project header is different ...

**Comment by phillipoertel** [comment]
@dottorer can projects with open tasks/supplies be closed? Working groups can't, they get an alert message.

**Comment by dottorer** [comment]
@phillipoertel I think if a project has open tasks / supplies we show a warning to tell them to close them out, like on WGs.

I will think about an indicator for the closed projects. Looking around, I noticed that the line display of closed tasks does not show them green, but the display of the individual task does how them green. Will open a bug for it.

**Comment by dottorer** [comment]
@phillipoertel Ideas for visualization:
- in the single project view we could prepend the word 'Erledigt: ' to the project title as we do with the tasks.
- for the list view of projects (both on the work group level and on the circle level), we could also offer the toggle to 'Erledigte Projekte...' and in that list show a small round green check box icon 

![image](https://cloud.githubusercontent.com/assets/14217285/18701468/11b377d8-7fdd-11e6-946e-a5c19b161f85.png)

**Comment by phillipoertel** [comment]
@dottorer Ok, sounds good.

**Comment by phillipoertel** [comment]
@dottorer feature is ready for review on staging!

**Comment by dottorer** [comment]
@phillipoertel Testing was very complete already. Looking good. 

Couple of thoughts:
1. I think we need to indicate it more strongly that a project is closed. Could we re-style its header to be closer to the task header and use 2 colors: light blue for normal and green for closed?
![image](https://cloud.githubusercontent.com/assets/14217285/18717410/10ca419c-8020-11e6-827d-06db97860d2c.png)

![image](https://cloud.githubusercontent.com/assets/14217285/18717167/6404b9ec-801f-11e6-9d9b-b85db562644d.png)

2. We could potentially leverage this in a better list view for projects:
![image](https://cloud.githubusercontent.com/assets/14217285/18717821/94aa259e-8021-11e6-9476-c2e009f933d5.png)
List view would show WG a project is in, number of open tasks and supplies and helpers (n out of m).

3. The current project icon really does not scream 'project' to me...

What do you think? Doable?

**Comment by dottorer** [comment]
@phillipoertel Tested. Looks good - some notes:

1. When deleting a project, we show a warning 'are you sure?', then we blow project and all included items away. We should tell them in the text that included tasks / supplies will be deleted.
2. Closed projects: Likely part of #413 but we need to decrase the counter in the leftnav (should only count open projects) and then move the project to the 'closed projects' listing.

Other than that basic state transition looks good. Closing.

**Comment by dottorer** [comment]
@phillipoertel In production, on the circle level I do not yet see the 'Abgeschlossene Projekte...' toggle in the list. I thought we had this implemented just like on the workgroup level, but maybe not deployed yet? Just checking...
