### ISSUE TITLE
iPad Sidebar Nits

### ISSUE THREAD

**Issue by phillipoertel** [lale-help/lale-help#392]
- [ ] content area scrolls (down) while menu is fixed
- [x] burger menu doesn't show despite menu being hidden

![content area scrolls while menu is fixed png](https://cloud.githubusercontent.com/assets/5188/16798478/7877fa16-48ec-11e6-9185-9c289bd86171.jpeg)
![burger menu not showing png](https://cloud.githubusercontent.com/assets/5188/16798479/78794696-48ec-11e6-9dce-71e2c8d398f2.jpeg)

**Comment by phillipoertel** [comment]
Screenshots from my iPhone 6 (376 x 667px) for comparision. Layout isn't perfect, but the side is usable without problems, burger-menu also always visible.

![img_0597](https://cloud.githubusercontent.com/assets/5188/16798734/ce2f1718-48ed-11e6-8c6b-ae51fdbd4e3c.PNG)
![img_0598](https://cloud.githubusercontent.com/assets/5188/16798735/ce313908-48ed-11e6-8eef-2f249ec76451.PNG)
![img_0599](https://cloud.githubusercontent.com/assets/5188/16798736/ce3259aa-48ed-11e6-9988-e14b2f889d33.PNG)
![img_0600](https://cloud.githubusercontent.com/assets/5188/16798737/ce3306de-48ed-11e6-8ba6-4d1b33b9d3ed.PNG)

**Comment by phillipoertel** [comment]
@dottorer 
- re. the burger nav not showing: I found an issue in the CSS, should be fixed. The sidebar should now be hidden in portrait mode, but visible in landscape. burger menu shown/hidden accordingly.
- re. the scroll issue: I can't reproduce this in the "simulator", and don't know what could be the reason, so it'll have to wait until we can test on the real thing.

**Comment by dottorer** [comment]
Leaving this where it is right now, responsive working pretty good for now. More to come when needed....
