### ISSUE TITLE
When new work group is created, organizer is set but not also added as member

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#394]
When creating a new WG and we select an organizer in the create screen, this user should also be listed as a member of the group:

![image](https://cloud.githubusercontent.com/assets/14217285/16949219/bfcf15da-4db9-11e6-9847-06643a8fa40a.png)

![image](https://cloud.githubusercontent.com/assets/14217285/16949225/d20dd434-4db9-11e6-9716-6ec6e25344a2.png)

**Comment by NolanChan** [comment]
Hi @dottorer , just FYI I think this one has been fixed already

**Comment by dottorer** [comment]
Yep, i think so too. Thanks!
