### ISSUE TITLE
DEMO bug: Cannot create new work group / project

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#395]
When adding a very first working group in a new circle (as admin), I encounter the following error: https://rollbar.com/lale-help-demo/lale-help-demo/items/4/ 

Can we look at this briefly?

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/17021231/f3692c8a-4f46-11e6-8dde-29bf02f30423.png)

**Comment by dottorer** [comment]
This does currently not occur in STG even for a newly created circle. I wonder what isdue of 'parent not created' the rollbar is referring to.

**Comment by phillipoertel** [comment]
I'll have a look this evening. 

Von unterwegs gesendet, deswegen kurz und evtl. mit Tippfehlern

**Comment by phillipoertel** [comment]
@dottorer just fixed the bug and pushed to all environments (demo, stg, prd), since all were affected.

The reason was: I had introduced a bug when adding the working group name validation in the last session. The way I put it, the working group needed to be *globally* unique, not unique per circle. Because of that the working group you tried to create was invalid (there already was a group "Betreuung" in another circle. The validation error went unnoticed though until the WG organizer role needed to be created. Since the working group was unsaved (and thus didn't have an id) you couldn't create a role for that WG, either, and that's the error message we finally got.

**Comment by dottorer** [comment]
@phillipoertel thank you for looking into that! Makes sense now and was part of the uniqueness cleanup then...

**Comment by dottorer** [comment]
@phillipoertel The exact same issue with globally unique names occurs for projects. Can we apply the same fix there? Is this also possible for tasks and supplies?

**Comment by phillipoertel** [comment]
@dottorer 

- the project constraints (a working group should not have two projects of the same name) look Ok to me. There actually already is a project with the name "Tutorenzeit - Lerncenter - Juli" in the working group 34 / circle 3; it was created on the 27th of June at 9:02am.

- task and supply names have no uniqueness constraints (remember tasks can be cloned, which preserves the original name).

**Comment by phillipoertel** [comment]
The rollbar issue for reference: https://rollbar.com/lale-help/lale-help/items/35/occurrences/14778044064/

**Comment by phillipoertel** [comment]
@dottorer the error when a project name already exists should be handled more gracefully though; I guess you got a complete error page instead of a helpful error message.

**Comment by phillipoertel** [comment]
Let me summarize what needed/needs to be done here:

1. Fix name uniqueness constraint for working groups (a working group name needs to be unique per circle)
2. When saving a project: improve error message / handling when project name has already been taken.

What doesn't need to be done:

1. change project name validation: a project name needs to be unique per working group, this is the way it's already implemented.
2. change task & supply name validation: there are no uniqueness constraints for these in place, you can create several tasks/supplies of the same name, if you like, even within the same working group.

**Comment by phillipoertel** [comment]
Reopening since I shouldn't close issues (closed it with the last commit by accident).

**Comment by dottorer** [comment]
This is no longer an issue. Closing.
