### ISSUE TITLE
BUG: System error when editing projects

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#398]
Matze found an issue in DEMO and STG: When editing a project, we receive an error. It sometimes does not occur, so it can be intermittent. But it basically happens steadily now. Error in https://rollbar.com/lale-help-demo/lale-help-demo/items/6/

**Comment by dottorer** [comment]
Sorry @phillipoertel but this one keeps us from preparing for an important demo to the LRA on Thursday and also for one at Montessori this week. Could we quickly look into it? I cannot see a problem with the data itself at first glance...

**Comment by phillipoertel** [comment]
I'll check tonight, shouldn't be too hard to find. 

Von unterwegs gesendet, deswegen kurz und evtl. mit Tippfehlern

**Comment by phillipoertel** [comment]
@dottorer All of the projects for which you got errors (22, 27, 28, 29) had no organizer role, so an error happens when trying to show the project.organizer.name. I just fixed that, assigning either you or Matze as organizer.

What's strange: assigning an organizer is mandatory in the create project form, so I don't know how a project got to that state. Could you ask Matze if he can still reproduce the steps? If he can't, the broken projects could have been created during the error described in #395 . The project + organizer role should be either created together or not at all, so I'd have to investigate further if that really is the source of error.

**Comment by Matthias-Lale** [comment]
@phillipoertel @dottorer I tried to create a new project in Monte DEMO (circle 13). As Admin I am in all WGs but in two. For the one I am not in the WG (WG Bau) I created a project. As you can see from the screen shots, no organizer is given by default:

![profect without organizer_1](https://cloud.githubusercontent.com/assets/17497825/17167118/94b1c122-53db-11e6-9905-33a6250e2e0d.jpg)

 I click on "create" button an it came screen shot 2:

![project without organizer_2](https://cloud.githubusercontent.com/assets/17497825/17167295/a852d648-53dc-11e6-9327-33d03eda350f.jpg)

The same happens, when I have already created the project "EKP ..." and the create a task in this project (of WG Bau). I could not select an organisator and in the next screen, the Admin is made as organizor (by teh way, I am logged in as AdminWalz, administrator). Everything works fine so far.

OK, I now I tried in WG Finanzen a new project: "Liste ehemaliger Schüler ..." and as AdminWalz I selected some else (user "Alphamonte") as organisator. I could create the project. Then I tried to edit the project and after pushing "Save", the system gave the error message.

Do you need some more testing?

**Comment by Matthias-Lale** [comment]
@phillipoertel @dottorer I just wanted to add another screenshot:

![project with organizer_3](https://cloud.githubusercontent.com/assets/17497825/17167746/fe7aca92-53de-11e6-92b5-47058246ed18.jpg)

And now quite interesting for me:
After the error message , I clicked on the back button in the browser and though first Alphamonte was chosen as organizer, now  in the screen "Matthias Walz" is given as organizer, who is not logged in currently:
![project with organizer_4](https://cloud.githubusercontent.com/assets/17497825/17167842/7e21401e-53df-11e6-8fc1-ce7fb89b058a.jpg)
If I changed a word in the description and then clicked on save, it works:
![project with organizer_5](https://cloud.githubusercontent.com/assets/17497825/17167890/ca54bbfa-53df-11e6-81f8-b7690cc33166.jpg)
Then I changed again the organizer to user "Alphamonte" and changed one word in the description:
![project with organizer_5](https://cloud.githubusercontent.com/assets/17497825/17167945/ffd18330-53df-11e6-9633-0d2a8e09307f.jpg)
 And again the error message did come up.

**Comment by Matthias-Lale** [comment]
@dottorer @phillipoertel Sorry, last screen shot was wrong, it should have been this one:
![project with organizer_6](https://cloud.githubusercontent.com/assets/17497825/17168087/ae1260ea-53e0-11e6-8f4a-de6262b57a74.jpg)

**Comment by phillipoertel** [comment]
@Matthias-Lale thank you for the extensive info. The WG you're creating the project in (WG Bau) doesn't have organizers nor members. I'm surprised about that, it shouldn't be possible -- there's a check for an organizer when creating a new working group, and deleting the last working group organizer role in the admin is also not possible (see screenshots below). 

The WG Bau was created two days ago, so you must have managed to get the WG to this state somehow; do you remember how? That would be really helpful for further debugging.

To prevent this error for the moment, make sure your working group always has at least one member or organizer, then that one can be chosen as project organizer.

![delete-last-organizer-role](https://cloud.githubusercontent.com/assets/5188/17169721/1d608172-53e9-11e6-845e-cb58f76fa25b.png)


![create-wg-without-organizer](https://cloud.githubusercontent.com/assets/5188/17169723/1d6f1f8e-53e9-11e6-937d-82997fcfd7a9.png)

**Comment by Matthias-Lale** [comment]
@phillipoertel as far as I can remember, I did all WGs with AdminWalz (sole user and administrator at this time). Then I changed in two WG the organizer to "Matthias Walz".
What is totaly strange, I have no idea why WG "Bau" is not listed in list of organizers:

![project with organizer_7](https://cloud.githubusercontent.com/assets/17497825/17170982/dbe08a34-53ee-11e6-930b-b4ff66731029.jpg)

Now I also tried to create a new WG "Tombola". An organizor was mandatory:
![project with organizer_8](https://cloud.githubusercontent.com/assets/17497825/17171221/f732e600-53ef-11e6-93f0-88a30e70f967.jpg)

Should I assign an organizer in WG "Bau"?

**Comment by Matthias-Lale** [comment]
@phillipoertel I just saw, that in one project there is no organizer, this refers to the screen shots above "Liste aller ehemaligen Schüler ..." I created this morning:
![project with organizer_9](https://cloud.githubusercontent.com/assets/17497825/17171791/7e31f568-53f2-11e6-8d16-2bd81a7db66f.jpg)
I tried to access this project by clicking on the name, but then there came the error message again.
I tried several ways to access the project (from WG, from overview) but always the error message.

**Comment by phillipoertel** [comment]
The system error happens because the project admin was removed when editing an existing project ... just fixed that.

**Comment by phillipoertel** [comment]
What's left to be done here:

* [x] deploy bugfix for "project admin is removed when updating a project" (on all servers, i.e. demo, staging, production)
* [ ] check and fix all projects that don't have an admin (on all servers)
* [ ] check why no admin is shown here: https://github.com/lale-help/lale-help/issues/398#issuecomment-235510470
* [ ] clarify if there are any other problems with Matze

**Comment by phillipoertel** [comment]
Regarding https://github.com/lale-help/lale-help/issues/398#issuecomment-235510470: the organizer field is empty because the WG Bau has no organizer. A WG must always have an organizer, so I assume this is a leftover from the bug #395, where working groups were created without organizer when an error happened.

To explain why "Admin Walz" (the user you're currently logged in as) was made organizer: when trying to create a project without organizer, we just use the currently logged in user. We didn't put much thought into this, as it should actually never happen (as I said, a WG must always have an organizer).

I'll change the project create form to show an error when no organizer is given.
And I'll also fix the WG Bau and assign an organizer.

**Comment by phillipoertel** [comment]
@Matthias-Lale as just discussed by phone I believe I fixed all bugs in this ticket (and updated demo.lale.help). When you find the time, please give me feedback if you still find problems with the projects. If you do, it would be best to open a new ticket, using this link: https://github.com/lale-help/lale-help/issues/new. Thank you!
