### ISSUE TITLE
DEMO bug: Error when clicking email button

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#399]
During the demo last Thursday we ran into a bug when clicking the 'accept' button in an email . We sent our an invitation using Find Helpers, but possibly that same user was already added manually as an assignee. Clicking the button then produced a hard error 

https://rollbar.com/lale-help-demo/lale-help-demo/items/10/

If this is a duplicate assignment constraint, we need to handle it more gracefully. Ideally the task page still open without error.

**Comment by phillipoertel** [comment]
@dottorer I'm not able to reproduce this error. I tried as follows:

- send out an invitation to a task to all working group members
- as member of the working group (Luke), sign up for the task **through the task page**
- as Luke, click the "accept" link in the email.
- result: no error, no duplicate volunteer role.

I also reviewed the code for the invite email, before creating the volunteer role it checks if there is one already. Do you remember how exactly this happened, or could you try to reproduce? 

The only thing I could imagine is that the "Accept" button in the email was clicked twice (or double-clicked) which lead to two concurrent requests. Those may be able to pass the Rails uniqueness constraint, but not the DB.

**Comment by phillipoertel** [comment]
I also tried opening the task in two browser tabs, clicking "I'll help" in the first works as expected, in the second I then get the flash error message "not allowed to volunteer".

**Comment by phillipoertel** [comment]
@dottorer this seems to be high priority, but I can't reproduce.

**Comment by dottorer** [comment]
This has not re-occured and we  cannot reproduce. Closing until we have better instructions...
