### ISSUE TITLE
Bug: Find helpers shows wrong count of work group addressees

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#400]
User reported issue: 
In a work group with 7 members (all of which are also organizers of that group), when we use the 'Find helpers' button it shows "0 helpers" as recipients of an email. However, when clicking the button, we send the right email to 6 group members (7 total minus the task organizer) and track that in the lalebot. We need to ensure we should the right recipient count.

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/18246726/d0f8a64e-736d-11e6-8387-3b1cd3d3ceda.png)

![image](https://cloud.githubusercontent.com/assets/14217285/18246729/d9f21370-736d-11e6-9bc8-86e0c0168567.png)

![image](https://cloud.githubusercontent.com/assets/14217285/18246732/e0efe9c2-736d-11e6-9388-2ac631a07f25.png)

**Comment by dottorer** [comment]
Screenshots available per email...

**Comment by phillipoertel** [comment]
Just confirmed this still happens: 

- in the working group invite, the WG organizers were deliberately excluded
- in the circle invite, both the circle admins and the WG organizers were excluded.

I adapted the code to include all of those in the invitations, as well.

**Comment by phillipoertel** [comment]
Just deployed the fix to staging, please review & close, or feedback.

**Comment by dottorer** [comment]
Reviewed, looks good in my test cases. CLosing.
