### ISSUE TITLE
When leaving a group, helper is removed from all groups.

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#406]
Helper was member in two groups and decides to leave group 2. Helper is removed from both groups. 

Of course leaving a group also removes you as a organizer of any groups, which leaves the group without organizer!

**Comment by phillipoertel** [comment]
@dottorer I was able to reproduce this and already fixed it on master.

**Comment by phillipoertel** [comment]
Now deployed to all envs.

**Comment by dottorer** [comment]
Works now. Closing.
