### ISSUE TITLE
Bug: Rollbar 26 - missing apple-touch-icon 

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#408]
See https://rollbar.com/lale-help/lale-help/items/26/

**Comment by phillipoertel** [comment]
The image /apple-touch-icon-precomposed.png is requested by iOS devices and used as a app icon (comparable to the favicon). Details: https://realfavicongenerator.net/blog/apple-touch-icon-the-good-the-bad-the-ugly/

As a quick fix, I added empty files for them, that'll make the error go away and display an empty icon for lale on iOS. 

@dottorer could you insert/link to a higher quality icon of lale here? I can then generate a proper apple touch icon (using this service: http://web-stuebchen.de/).

**Comment by dottorer** [comment]
![laleiconcolor60](https://cloud.githubusercontent.com/assets/14217285/18631672/a211d6c8-7e73-11e6-8654-13f7b63fce3f.png)

@phillipoertel will this icon work? I can send it to you in any size / res....

**Comment by phillipoertel** [comment]
@dottorer could you provide me with a 180x180px version? That would be simplest and most compatible, according to https://mathiasbynens.be/notes/touch-icons.

**Comment by phillipoertel** [comment]
Icon works on production: https://app.lale.help/apple-touch-icon-precomposed.png

**Comment by dottorer** [comment]
I tried to add demo.lale.help or staging.lale.help to the iPhone home screen. It does not yet show the icon: 
![img_5439](https://cloud.githubusercontent.com/assets/14217285/18666932/b187f04a-7f2e-11e6-8e4b-497e827cd570.JPG)

Did we deploy yet? Should that not show the Lale icon we added in?

**Comment by phillipoertel** [comment]
@dottorer same with production, I just noticed. I'll check.
I'll move the issue back to the started column :-/

**Comment by phillipoertel** [comment]
After some more fiddling I got it to work (bottom right icon):

![image1](https://cloud.githubusercontent.com/assets/5188/18673668/f08b0002-7f4c-11e6-82a0-d86b52484405.PNG)

**Comment by dottorer** [comment]
Tested and works - thanks. Closing.

**Comment by dottorer** [comment]
@phillipoertel Seems to still be happening in some envs: https://rollbar.com/lale-help/lale-help/items/26/ 

Did we not deploy everywhere?

**Comment by phillipoertel** [comment]
Yes, the fix is deployed to demo and prd. 

This is a request by the GoogleBot to https://app.lale.help/.well-known/apple-app-site-association (see the details at), not the touch icon. I don't understand why Rollbar maps it to that. 
I just heard about this request by Google, I don't think it's essential we return something useful there; compare: http://webmasters.stackexchange.com/questions/85674/why-does-google-request-apple-app-site-association-from-every-domain-on-the-serv

**Comment by dottorer** [comment]
Let's ignore the google bot. And rollbar. Closing.
