### ISSUE TITLE
Setup xxx@lale.help email accounts in GoDaddy / CloudFlare

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#41]
We should setup:

info@lale.help
ralf@lale.help
banking@lale.help

and route them all to ralf.schroeder@gmail.com for now.

**Comment by phil-monroe** [comment]
@dottorer: Now that your email is setup, you will need to create the aliases inside of Office 365

**Comment by dottorer** [comment]
I have ralf@lale.help and info@lale.help working as 2 separate exchange email accounts in goDaddy. We are using "info" for anything on the website that refers to email.
