### ISSUE TITLE
Closed tasks do not appear green in list view

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#412]
I noticed that the line display of closed tasks ('Erledigte Aufgaben...') does not show them green, but the display of the individual task does how them green.

**Comment by phillipoertel** [comment]
@dottorer fixed and testable on staging.

**Comment by dottorer** [comment]
@phillipoertel Tested it but when clicking on 'closed tasks...' it only shows an empty partial. Same on supplies. Still not quite there?

**Comment by phillipoertel** [comment]
@dottorer I can't reproduce the error; testing myself on staging works as expected. Which circle or working group are you trying it in?

**Comment by phillipoertel** [comment]
Here's a short GIF to illustrate:

![sep -23-2016 10-32-37](https://cloud.githubusercontent.com/assets/5188/18779425/5150ea7c-8179-11e6-9d2d-36ac0e38bbb9.gif)

**Comment by dottorer** [comment]
@phillipoertel still seeing this behaviour in https://staging.lale.help/circles/3/working_groups/11 

Strange...

**Comment by dottorer** [comment]
Problem exists in the same way in both Chrome and Edge.

**Comment by dottorer** [comment]
Was missing translation, works now. Closing.
