### ISSUE TITLE
Improve display of projects details view and projects list view

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#413]
With #388 we are giving a status to projects and need to also improve the visualization. 

1. re-style its header to be closer to the task header and use 2 colors: light blue for normal and green for closed
![image](https://cloud.githubusercontent.com/assets/14217285/18718613/75fc4886-8024-11e6-9c41-8d5a3702f8cd.png)

![image](https://cloud.githubusercontent.com/assets/14217285/18718621/7f73f4f4-8024-11e6-8f44-8b2bc2acccd5.png)

2. leverage this in a better list view for projects:
![image](https://cloud.githubusercontent.com/assets/14217285/18718642/8b6559c4-8024-11e6-80d0-1729fef17a4a.png)

List view would show WG a project is in, number of open tasks and supplies and helpers (n out of m).

The current project icon really does not scream 'project' to me...

**Comment by phillipoertel** [comment]
Updated spec for project lists:

- [ ] don't show supplies (0) if there aren't any (same with tasks)
- [ ] colorize project icon according to open/closed status (same colors as tasks/supplies)
- [ ] show WG name only when in circle context (otherwise it's obvious)

**Comment by dottorer** [comment]
@phillipoertel Let's try this as a new icon for projects: http://cdn.onlinewebfonts.com/svg/img_446233.svg 

It should be similar in appearance and scale ok.

**Comment by phillipoertel** [comment]
@dottorer I implemented as requested and deployed to staging for review.

**Comment by dottorer** [comment]
@phillipoertel Good start, here are a few notes after testing it:

1. Task line item view is now skewed:
![image](https://cloud.githubusercontent.com/assets/14217285/18813769/238c1934-8306-11e6-868a-5c0826942ccd.png)

2. Count for required total / assigned helpers should only look at open tasks (ignore closed tasks):
![image](https://cloud.githubusercontent.com/assets/14217285/18813783/6b603614-8306-11e6-8cba-267f5eedba7a.png)

3. Rework line item view a bit.
3.1 Icon should be overlaid to badge. Badge styled similar to tasks. Need to discuss if we can keep month display there, which is mostly visual appeal.
3.2 Counts for tasks and supplies should be using check icon (https://useiconic.com/icons/task/) and list open tasks / total tasks. This way the display is consistent in spacing and less cluttered.
3.3 Discuss if project colors are sufficient as blue / green.

![image](https://cloud.githubusercontent.com/assets/14217285/18813907/910de290-830a-11e6-9dac-d2b5d5207914.png)

Will do more testing, but also need to include translations...

**Comment by dottorer** [comment]
Not trying to create scope creep, but maybe we can consider #330 in order to make a meaningful date range for the badge header. Thoughts?

**Comment by phillipoertel** [comment]
Todos:

- [ ] Task line item view is now skewed:
- [ ] Count for required total / assigned helpers should only look at open tasks (ignore closed)
- [ ]  line item view: Icon should be overlaid to badge
- [ ] Counts for tasks and supplies should be using check icon
- [ ]  Discuss if project colors are sufficient as blue / green.

**Comment by dottorer** [comment]
@phillipoertel Looks nice! Only think i saw so far is that project list should be sorted by months in badge header asc. (Not alpha).

And maybe add a space between the dot and the "in workgroup".

**Comment by phillipoertel** [comment]
@dottorer done as requested and reviewable on staging.

**Comment by dottorer** [comment]
@phillipoertel Looks really slick now - great job. Only thing I am wondering in the overall projects list we display completed projects and not the toggling between open / closed projects like on the workgroup level. Is this intentional?

![image](https://cloud.githubusercontent.com/assets/14217285/18870343/7b5fa44a-84b0-11e6-86af-29752f909e92.png)

**Comment by dottorer** [comment]
@phillipoertel looks perfect now! Closing - WDL.
