### ISSUE TITLE
Newly appointed admin has incorrect admin status

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#415]
In PROD:

1. created new circle (circle 11). circle admin is user 179.
2. then I use the join URL for circle 11 and add another user (no approval required).
3. the new helper is successfully added to the circle as user 180.
4. then I have the current admin also add the new user for the role of admin. The status of this role is 'nil' hence the display is broken.
5. Also the button to remove the admin role from user 180 is not displayed, which should be possible since we still have one valid admin.

![image](https://cloud.githubusercontent.com/assets/14217285/18869179/7b43072c-84ab-11e6-8cbc-9bb9127d12ea.png)

**Comment by phillipoertel** [comment]
**Todos**:

- [x] set a new admin role to active by default
- [x] only the last *active* admin role can't be deleted; blocked admin roles can be deleted.

**Comment by phillipoertel** [comment]
@dottorer implemented; can be reviewed on staging.

**Comment by dottorer** [comment]
@phillipoertel Tested in STG in circle 56. Works great now. Did we fix the existing PROD, DEMO and STG instances via SQL?

**Comment by dottorer** [comment]
All instances have been fixed in STG, PROD and DEMO by SQL. Closing.
