### ISSUE TITLE
Cannot add document for work group

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#417]
While I can still as an admin add documents on the circle level, I can no longer do so as admin or group organizer on the group level.

![image](https://cloud.githubusercontent.com/assets/14217285/19228821/24a8a944-8ec9-11e6-9cbc-28d45e6fef09.png)

It displays the button "Dokument erstellen" and clicking it does nothing but switches back to the group dashboard. On the circle level, we get the button "Datei hochladen" which opens the upload dialog.

**Comment by dottorer** [comment]
@phillipoertel Now reported by 2 production customers. Would be good to take a quick look and see if it is an easy glitch...

**Comment by NolanChan** [comment]
Hi @dottorer , I'm unable to reproduce this on the latest master. Are there some specific steps to take? I can create documents in working groups using the Admin profile or Working Group organizer

**Comment by phillipoertel** [comment]
Was fixed already; check the last commits :-)

Von unterwegs gesendet, deswegen kurz und evtl. mit Tippfehlern

**Comment by dottorer** [comment]
Sorry, was not able to close this out as fixed yet :-) done now...
