### ISSUE TITLE
Translation missing on flash for closing task

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#418]
Translation missing for object bind variable on flash for closing task

![image](https://cloud.githubusercontent.com/assets/14217285/19415895/f4de5964-937f-11e6-87bd-821098e7da87.png)

**Comment by diegoaad** [comment]
Assigned this one to myself as it's an easy/simple one, just to shake the rust off.

**Comment by dottorer** [comment]
Thanks. Merged!
