### ISSUE TITLE
Descr field for work group too short

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#419]
The description field for work group does not allow enough details to be useful:

![image](https://cloud.githubusercontent.com/assets/14217285/19415919/48f192d2-9380-11e6-94c2-c75676911b11.png)

We need to increase it to a meaningful size and handle the display on the WG dashboard gracefully.

**Comment by dottorer** [comment]
@diegoaad Maybe something to look at as well? We could use a longer description , but need to figure out how to fit it in the pages where it is displayed...

**Comment by diegoaad** [comment]
Sure I'll take a look on this one as well. It should be simple to fix, but I have to make sure I don't mess up with any css.

**Comment by diegoaad** [comment]
The field was set to max 200 chars. I've increased it to 2000, but as you said we'd need to figure how to fir in pages where displayed. I've changed the view working group page to increase the text area a little bit and have a vertical scroll bar if it goes beyond the size of the text area. I'm not sure where else this description would be shown, apparently it's only on this page. Let me know what you think:

![workinggroup_description](https://cloud.githubusercontent.com/assets/4204139/20546349/c86472b2-b114-11e6-8951-78d69111326c.gif)

**Comment by dottorer** [comment]
I think this looks real good. I don't think we show the description anywhere else for workgroups. But we have the exact same thing on the circle. Could we make it the same behavior there as well?

**Comment by dottorer** [comment]
Also, would need to check how the scrolling works on mobile devices or if we need to truncate there. We can check once its in a review app.

**Comment by dottorer** [comment]
@diegoaad I think this looks pretty good. I tested the review app on IE and Edge. 

Also on iPad, where you can sort of scroll a bit, but it does not indicate a scroll bar there visually. I think it is ok though, if folks really must add super long descrs...

So I'd say I can merge this PR if you are ok.

**Comment by diegoaad** [comment]
Sounds good. Feel free to merge the PR 👍

**Comment by dottorer** [comment]
Merged. Thanks man!!!
