### ISSUE TITLE
Open task counter on project list shows wrong count

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#421]
The first number for the badge with the check mark icon should show open out of total tasks/supplies inside the project. It seems to only show the total number twice:

![image](https://cloud.githubusercontent.com/assets/14217285/19652194/30150578-9a10-11e6-8d63-1899d772bcce.png)

**Comment by NolanChan** [comment]
PR'd a possible solution! Is there someone who is in charge of code reviewing?

**Comment by dottorer** [comment]
@NolanChan Verified in review app, merged in master, deploying asap. Well done!
