### ISSUE TITLE
No longer default task location from helper circle location

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#428]
Currently we default the task location from the circle location, but this is more often wrong than right and users have to delete this default all the time. Annoying. We should stop this default.

Instead we should implement #138 at a later stage.

**Comment by dottorer** [comment]
@diegoaad this should be a super quick fix to turn it off, right? wonna look? :-)

**Comment by diegoaad** [comment]
@dottorer yes, it should be simple enough. I took a look already, and the same form is used for new tasks or for editing a task. I kind of have coded the change directly on the form view, but doesn't feel right. I'll code it later to change the controller or the model to not return a default location for new tasks.

**Comment by diegoaad** [comment]
I think I found the right place to fix it. Will create a PR for that.

**Comment by dottorer** [comment]
@diegoaad I realized that the location is a required field. If we do not default it, users must enter something to save the task which could be even more painful. Could we make the field 'Location' not required on all the forms to add or edit tasks or supplies? Could we check if there is any other dependency on this field being there?

**Comment by diegoaad** [comment]
Sure, I think it should be really simple to make it not required since they all share the same form. But I have to check what's the impact of not having a location for a task.

**Comment by dottorer** [comment]
Hi @diegoaad I am ready to release the latest build out to PROD but I already merged this fix for the default into master. I don't want to release it with location as required if we don't default it anymore, but similarly am not sure where we might need location to be present. Is there any chance you could look into this and see what happens if we make it non-required? Would you have a little bit of time?

I really want to get the export features and other goodies into PROD before xmas...

**Comment by dottorer** [comment]
Hi @diegoaad Any chance we can look into this to see what breaks if we leave the location field empty on tasks / supplies? If it is complicated we might revert the merge until we know. Trying to tie up the bundle for a next PROD release...thanks and greetings to Brazil!

**Comment by NolanChan** [comment]
From my initial observation,`primary_location` (retrieved from the form) and `location_assignments` (which is created from `primary_location`) don't seem to be used in anything crucial for tasks or supplies, but another look would definitely be good

**Comment by dottorer** [comment]
After verification of making location not required on tasks and supplies, pushed to PROD.

Thanks everyone!
