### ISSUE TITLE
Improve layout and usability of projects

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#432]
Based on deep user feedback, we need to improve the way projects are represented in Lale and can be interacted with. Here is a new design mockup with changes required:

![image](https://cloud.githubusercontent.com/assets/14217285/20935743/48b38590-bbe0-11e6-8648-fd3fce27abff.png)

![image](https://cloud.githubusercontent.com/assets/14217285/20935764/5af5b944-bbe0-11e6-9a11-944680b542d1.png)

![image](https://cloud.githubusercontent.com/assets/14217285/20935771/6700691e-bbe0-11e6-95f5-b534050a9764.png)

- [x] Create 4 tabs under the title/descr area: 2 tabs for tasks and supplies, one for comments, one for stats (later we will also have 'Documents' here and attach files to projects as in #337)
- [x] on the task tab, add a button to directly add tasks inside this project. When clicking it, the task is pre-populated with the project and working group which cannot be changed.
- [x] on the supply tab, add a button to directly add supplies inside this project. When clicking it, the supply is pre-populated with the project and working group which cannot be changed.
- [x] Sort all tasks and supplies by the due date field showing the newest first.
- [x] When opening a task from the task list, we are presented with the task page. When closing it, we should be taken to the task tab of the project home page (same for supplies). This is the page we came from and makes sense to the user.
- [x] Offer ability to comments on the project by re-using the comments section. No notifications will be sent when comments are added.
- [x] Add tab for 'Stats' showing the existing sign-up stats. Possible add few more metrics such as 'Last task assigned at' and 'Last task completed'

Also, we should implement #330 as an improvement.

**Comment by dottorer** [comment]
@diegoaad Per our chat yesterday, I simplified the design / UX aspect of the layout somewhat to be in line with the currently applied layouts. Might be easier to do this way. Added the comments in there as a requested feature. Take a look and let me know what you think...maybe we can find someone for it.

**Comment by jprokay** [comment]
@dottorer can you send me or add the icon for the description? I have a prototype of the following parts of the new layout:
- Moved working group and period underneath the description
- Created Comments tab with a box for adding comments and a list of previous comments
- Created Stats tab containing the basic stats for helpers, tasks, and supplies

**Comment by jprokay** [comment]
Also, any guidance on the sizing of text in the header of the project would be much appreciated!

**Comment by dottorer** [comment]
Hi @jprokay we could try one of the following icons...

![img_0786](https://cloud.githubusercontent.com/assets/14217285/21516940/02814556-ccdb-11e6-8825-6482dae2f7b9.PNG)
![img_0787](https://cloud.githubusercontent.com/assets/14217285/21516941/02b100d4-ccdb-11e6-91d9-70803678dec3.PNG)

**Comment by dottorer** [comment]
Ooops, these uploaded quite large so we will need to size them accordingly...

The title size should be the same as for tasks. The font size for the description should be legible but not taking too much space.

For the comments tab, i assume you reused the existing commentaboe feature like we do for tasks today, right? 

Looking forward to seeing your prototype in a review app :-)

**Comment by jprokay** [comment]
@dottorer what gems are used to encode the icons? I resized and converted one to a SVG, but I am not sure how I expose it as a variable in:
app/assets/stylesheets/settings/_icons.scss
I assume the \f119 assigned to $lale-icon-supply automatically happens with the use of some gem? 

Everything else is pretty much good to go!

**Comment by dottorer** [comment]
I think we encoded some icons in a font, too. @phillipoertel did that and might be best to show how.

We could add the icon later, too, if we want to proceed for now on the PR.

**Comment by dottorer** [comment]
@jprokay @phillipoertel 

Tested this much improved way for projects UX in the review app. Here are the missing items:

- [ ] translations to German for field 'Description', 'Add xxx' buttons and 'Stats' tab
- [ ] Icon for description needs to be added
- [ ] Layout of header table not quite using all the space it should. 
![image](https://cloud.githubusercontent.com/assets/14217285/21762738/b58c7dc2-d65a-11e6-9651-4644207e4287.png)
- [ ] When opening a supply and then navigating back, we are taken to the Tasks tab, not the 'Supplies' tab
- [ ]  spacing of new 'Add task' button with the toggle for 'completed tasks...' needs adjustment (same for supplies)
![image](https://cloud.githubusercontent.com/assets/14217285/21762714/9f8e520c-d65a-11e6-8efa-1be803748d64.png)
- [ ] Invite buttons should not be tied to the horizontal level of the tabs, but be under the 'Edit project' button
![image](https://cloud.githubusercontent.com/assets/14217285/21762773/e03fff1c-d65a-11e6-8e59-78299dacbf6f.png)
- [ ]  Name of project organizer should be a link to the helper, ideally with the hover over popping out
![image](https://cloud.githubusercontent.com/assets/14217285/21762919/897744b4-d65b-11e6-8b6d-213bf2fe9953.png)

Mostly spit & polish at this point! :-)

**Comment by phillipoertel** [comment]
FYI @jprokay I just documented how to add icons to the font: https://github.com/lale-help/lale-help/tree/projects_layout#adding-icons-to-the-lale-iconfont. 

I'm working on the issue right now, added the icon and will do some more; hope we don't step on each other's toes?

**Comment by phillipoertel** [comment]
@dottorer The project dashboard has working group and organizer name in one row; task and supply pages have them in separate rows (please compare screenshots). Should I update task and supply to also use only one row, or stay with the existing layout?

*Project*

![bildschirmfoto 2017-01-09 um 16 09 25](https://cloud.githubusercontent.com/assets/5188/21771134/78c5c3d6-d686-11e6-8acc-3e5f08f5489a.png)

-----------

*Task/Supply*

![bildschirmfoto 2017-01-09 um 16 09 41](https://cloud.githubusercontent.com/assets/5188/21771135/78c76c40-d686-11e6-80ab-8f2b98223c6d.png)

**Comment by phillipoertel** [comment]
@dottorer btw. the sentence "{working_group} organized by {user}" is a little confusing since we display the *project admin* there, rather than one of the *working group* organizer(s). 
In practice this probably won't cause problems since a project admin needs to be a working group organizer (as of now).

**Comment by dottorer** [comment]
@phillipoertel I think the new one-line version from the projects should be used in task/supply as well to make it cleaner and consistent. I think we could leave a bit more spacing before the 'organized ...' and after the '... by'. 

Thinking more about it, it seems that the most important info is who organizes the project (or task/supply), secondary is the working group this is in so we have a quick link to it. With this in mind, we might change to a one line version composed of:

- ![image](https://cloud.githubusercontent.com/assets/14217285/21773743/7bbab79a-d690-11e6-99be-0cf73b596283.png)
- 'Organized by' / 'Organisiert von' in large font
- Initials circle + organizer name as link
- ' in working group' / ' in Arbeitsgruppe'
- working group name as link

This should work consistently in project / task / supply and clean it up a bit.

What are our thoughts?

**Comment by dottorer** [comment]
@phillipoertel Please add a thin frame around the invite buttons to make it more consistent with task/supply...

![image](https://cloud.githubusercontent.com/assets/14217285/21799684/94b3bfe6-d71a-11e6-97a7-f78dcd19f467.png)

**Comment by phillipoertel** [comment]
@dottorer what would the area above the buttons look like then? Just adding a border around the buttons wouldn't make it consistent with to task/supply, since there's no box title and user badges. I didn't manage to make this look good ...

**Comment by dottorer** [comment]
Merged and ready to deploy...thanks @jprokay and @phillipoertel !!!
