### ISSUE TITLE
In leftnav sort working group by alpha ascending

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#434]
Currently the working groups are listed by their ID (= time of creation), which is not helpful to the user.

![image](https://cloud.githubusercontent.com/assets/14217285/20858804/cc79037c-b94d-11e6-9805-3b70924f99ab.png)

They should be sorted by alpha asc, both above and below the line (indicating where a user is member).

**Comment by dottorer** [comment]
@diegoaad small fix?

**Comment by NolanChan** [comment]
Left a comment in the PR as to the appropriateness of my fix

**Comment by dottorer** [comment]
@NolanChan works like a charm. Merged and pushed to STG / DEMO. PROD on next scheduled release.

THANKS!
