### ISSUE TITLE
On sign up form change default language to German

### ISSUE THREAD

**Issue by diegoaad** [lale-help/lale-help#438]
Let's set it to German by default and skip the check for browser's locale logic.

**Comment by phillipoertel** [comment]
Hi @diegoaad after discussing with @dottorer, I did the following:
- make "German" the first option in all select form elements
- leave the locale check unchanged; it's already quite smart. The browser's locale is only used as last resort, before it checks if there's a circle and uses that language; see https://goo.gl/szMCQO

**Comment by dottorer** [comment]
Fixed in recent deployment. Nice!
