### ISSUE TITLE
Spike: Email invites for large project potentially causing performance issues

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#441]
![image](https://cloud.githubusercontent.com/assets/14217285/20937374/faf2a640-bbe6-11e6-87bd-3c0689f98e19.png)

For a project email invite through Mandrill, we might encounter a severe performance degradation when the target email audience is large. This happened in PROD for a group of roughly 60 helpers that were invited to a project.

**Comment by dottorer** [comment]
@phillipoertel Do you think this could be a recurring pattern for Mandrill calls? The Rails app failed when the Mandrill service took too long, but the email were in the end sent (in Mandrill logs).

**Comment by phillipoertel** [comment]
It would be best to always send the invitations asynchronously. Maybe Mandrill supports that out of the box; if not, use a queue system like delayed_job or sidekiq. Both can be used through Rails' ActiveJob interface, IIRC.

**Comment by dottorer** [comment]
Closing based on @phillipoertel's research of options with decision to implement sidekiq worker process for delayed email delivery. See implementation in #449.
