### ISSUE TITLE
Setup active admin dashboard for lale-help

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#46]
Need to setup active admin dashboard so we can see and possible edit instance level data. Also we should get some initial meaningful metrics in place for our staging and finally prod systems.

**Comment by dottorer** [comment]
@tmandke @phil-monroe As we now open up a bit more to other sample users, it would be good to have visibility into usage and data being created in both staging and in app. Is is hard to setup the admin dashboard for these?

**Comment by posixpascal** [comment]
I setup active admin & will add the required modules to make instance level data editable, viewable and searchable.

**Comment by tmandke** [comment]
@dottorer list the metrics and we can set them up. Its not difficult for the most part (we will pick the ones that are easy for the first pass).

**Comment by dottorer** [comment]
completed in dev - works great!
