### ISSUE TITLE
When adding a new task inside a work group, correct workgroup field must be preselected and non-enterable 

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#467]
User 'Karl May' (user4@lale.help) is organizer of work group 'Arbeit'. If he selects 'Add task' within the group home page:
![image](https://cloud.githubusercontent.com/assets/14217285/24332636/65be6e78-124a-11e7-874b-093e99a90ba2.png)

The work group is still selectable and could be changed. 

![image](https://cloud.githubusercontent.com/assets/14217285/24332644/858996e2-124a-11e7-86bf-467400646b0d.png)

It should be defaulted to the work group where the button was pushed and be grayed out.

Also, if Karl goes to his other group 'Betreuung' and hits the in-group 'add task' button, not 'Betreuung' is selected but the first 'Arbeit' again. This is not working as intended.

**Comment by dottorer** [comment]
Tested in https://staging.lale.help with 'user4@lale.help' and password 'lalehelp'.

**Comment by dottorer** [comment]
Same is true for supplies and projects.

**Comment by mkristian** [comment]
hmm - all three tabs follow the same pattern and go to an url where the context of the working-group gets dropped. the fix would mean to add new endpoints which carry the work-group id and propagate it to the underlying logic. I do not have a feeling how big a change this is, but could be straight forward as the current code does not need much change and the new controller should be able to reuse the existing code.

**Comment by dottorer** [comment]
I believe this was working correctly at least partially before. Also, we do this in the context of projects when we create a task inside the project and the work group is preselected. Maybe we just have a small glitch somewhere...
