### ISSUE TITLE
Variable |*SUPPLY_LOCATION*| not passed to Mailchimp

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#468]
For the template "de/supply/supply_invitation" in MailChimp the variable |*SUPPLY_LOCATION*| is not populated.

![image](https://cloud.githubusercontent.com/assets/14217285/24332754/73bb0764-124c-11e7-9b55-7fe2a2e78f1f.png)

All others are passed in fine:

![image](https://cloud.githubusercontent.com/assets/14217285/24332764/821f56e8-124c-11e7-9844-f9fd1aba6778.png)

**Comment by mkristian** [comment]
c9d221a6286a42aedcc32a3738a104531f32309a might fix this issue. needs to be tested on staging.

**Comment by mkristian** [comment]
@dottorer do not know how to verify this on staging - not sure how many emails I sent to how many people.

**Comment by dottorer** [comment]
Will test soon, this is easy to verify in Staging.

**Comment by dottorer** [comment]
Tested in Staging - works great now!
