### ISSUE TITLE
Uploaded document for project cannot be retrieved

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#469]
When adding a document to a project, the upload works, but the file  cannot be retrieved again:

![image](https://cloud.githubusercontent.com/assets/14217285/24332809/27594df8-124d-11e7-9770-e7c676fc75e1.png)
 
![image](https://cloud.githubusercontent.com/assets/14217285/24332814/3c51b39e-124d-11e7-9912-b701cf7f0d4f.png)

**Comment by dottorer** [comment]
It seems like none of the documents can be retrieved now in Staging so it might be something generic with the S3 storage.

**Comment by mkristian** [comment]
routing for the files show were at the wrong place

**Comment by dottorer** [comment]
@mkristian File retrieval for all documents *except* from projects work now.

On Projects, I still get error:
![image](https://cloud.githubusercontent.com/assets/14217285/24587991/454a3304-17c0-11e7-9b10-b96b025ff70b.png)

![image](https://cloud.githubusercontent.com/assets/14217285/24587994/51fc7300-17c0-11e7-88d9-1c7dae9cd33b.png)

Login: "user4@lale.help" / "lalehelp"
Go to project "Gemeinsamer Besuch Welcome Cafe München" and try opening 'Logo_2' file

**Comment by mkristian** [comment]
:(

thought I verified it locally - have a look again.

**Comment by NolanChan** [comment]
Hi @mkristian , are you on slack? I wouldn't mind looking into this so I can re-familiarize myself with the code :)

**Comment by dottorer** [comment]
This is probably something with a wrong pointer to the S3 storage so hopefully easy to fix. More like a glitch.

But would be cool if you could look at the document features from the epic if you have some cycles....:-)

**Comment by mkristian** [comment]
@NolanChan I am on slack and gitter and gmail chat during the day. all these missing documents are due wrong or missing routing and wrong links: see https://github.com/lale-help/lale-help/commit/1ada25b01aa37a22b3eb7fdae7836162a8575f0f but this seems to be missing something else I changed for the projects - similar things: missing routing and wrong links

**Comment by NolanChan** [comment]
Hey mkristian, not sure if I could find you on slack. Could you message me? Also I won't be able to work on this until the weekend, so don't let me hold you up if you can fix it before then.

**Comment by mkristian** [comment]
@NolanChan honestly I have no idea even how to find you. just using and used slack in closed team channels. Probably will fix it before the weekend. I will let you know if not

**Comment by NolanChan** [comment]
@mkristian are you on https://lale.slack.com?

**Comment by mkristian** [comment]
nope - I would need an invite for this - as far I understand slack ;)

**Comment by dottorer** [comment]
What's your preferred slack handle for this? I can add you for ease of comms...

**Comment by mkristian** [comment]
meier.kristian@gmail.com for slack

**Comment by mkristian** [comment]
fixed via 34cfccaf5a83753d7e8c7701e744799b7a7318d7

e3d2d4d14830c270a97beb51361a93329fb7cce9 removed the edit button as it was not working. other file upload list do not have this button. removing it makes them all consistent. and you always can delete and reupload it anew. 

if the edit is something we want to offer we can revert the this commit and fix it and add the 'edit' button for other document uploads as well.
