### ISSUE TITLE
public Helper List / Organizer List 

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#48]
For the circle.admin we need to provide a list view of all members that have signed up for a circle. 

This could be grid like display of all circle members with columns for 
* lastname
* firstname
* in workgroups
* address, 
* homephone, 
* mobile, 
* email, 
* active since (i.e. when they registered with the circle), 
* last logged in, 
* last task completed.

- Ideally faceted search on top of page to reduce down to smaller set of circle.members (i.e. filter by workgroup membership, certain language skills, etc.)
- easy function to print to PDF and to export to XLS/csv for any result set in the grid (all or filtered).

**Comment by dottorer** [comment]
@jamesfan Hi James, would you have interest and time to create an initial visual design for such a list view? If we find a better way to represent circle members, please consider, list was just a suggestion.

Number of circle members can range anywhere from 10 to several hundreds (300 max I'd presume).

**Comment by jamesfan** [comment]
@dottorer : just chatted with @stephanerangaya and he tells me we're still kicking around visual design ideas as per your _Thoughts on visual design ideas_ doc. I'll try to help out with that first and then come back to this roster page after we've settled on an overall visual design.

Presenting this page as a list view makes sense, though. I'll start with that approach first.

**Comment by dottorer** [comment]
Very good, I think Stephane is planning to wrap up a new visual design that unites all of the good concepts we had in flight so far. However, I think many of these changes will affect overall flow and appearance more than layout of specific pages. But if you are in sync with him, then we can get the page design done in the new style. 

Would it be fair to associate your name with additional page designs we are pending so Phil's team and kick off next week? I have sent some your way, but didn't want to overwhelm you with requests. I was just going by the nice designs you had done user profile, circle page, etc..

**Comment by jamesfan** [comment]
Glad you liked the designs I put together earlier! Truth be told, I’m more of a UX guy than a visual design guy. I can put together visual designs in a pinch if I have something to start with (as was the case with the user profile and circle page), but I generally stick with the more preliminary wireframe stage.

The next few days are a busy time for me, but I can commit to producing wireframes for the roster page and likely a visual design based on the new style. I’m thinking wireframes early next week followed by a visual design shortly afterwards based on feedback. Anything beyond that depends on how things go at work — I’ll keep you posted.

**Comment by dottorer** [comment]
Assigning to Phil what he is working on already as mvp1 work.

**Comment by dottorer** [comment]
Hi @diegoaad : based on the awesome new public directory, this one is the version shown to the circle administrators only. So the idea is they get to see ANY helper listed (not just the public ones). This gives them the total list. SHould be a quick cloning/tweaking of the existing directory page. 

Is it possible to have this appear for admins instead of the public directory? So we don't have 2 links in the left nav for an admin...

**Comment by diegoaad** [comment]
Sure it makes sense to have 2 different listing of directory. So just to clarify:
- As a Circle admin, I can see a Directory which lists all members in my circle including the ones flagged to not show in public directory. The directory should present the following info: name (later link to public profile) + small initials icon, working group, address, phone, e-mail, active since, last login and last completed task.
- As a regular helper, I can see a Helpers List that lists all public members in my circle. The Helpers List should present the following info:  name (later link to public profile) + small initials icon, working group, address, phone, e-mail

Does it make sense? If so, I guess we just make the current Directory a page only for Admins and change the initials icon to be smaller.
Then we create a new page for Helpers List which will be available only when Directory is not available (ie. when user is not an admin). This Helper list will follow the design of the Directory but without the last 3 columns which I believe are more interesting for admins.

Besides that, I believe we might want to change the Organizer listing to be like the Helper List, and not have the 3 last columns (active since, last login and last completed task). In the case of Organizers, I wonder if we want to show their role in the circle or working groups. What do you think?

**Comment by dottorer** [comment]
Yep, all makes total sense...

**Comment by dottorer** [comment]
@kristysnet This is pretty much done in the branch 'helper-list'. Unfortunately @diegoaad is running out of time to complete it, so we need someone to just wrap it up and push it out. Maybe you can take a look and we can finish this up together. Diego can let you know what is missing from completion...Thanks!

**Comment by dottorer** [comment]
@phil-monroe Here is the detailed spec for the helper list and organiser list:

Status today:
![image](https://cloud.githubusercontent.com/assets/14217285/13284054/08332428-daf2-11e5-827c-09b52047a803.png)


## 1. Helper List
This list has 2 functions and versions, under the same leftnav link:
### 1.1 Helper List for all members
This should list all circle members that have marked their profile public.  Order by last name asc. If columns do not fit on one page, find elegant horizontal scroll preferably styled like scrolls in slack. Ideally each column should be sortable by the header.
It should list the following columns:
-  small initials icon & name, which links to the public profile page (hover over should work correctly on each line)
- working groups the helper is member of (comma separated, line feed for each group, clickable to open group dashboard)
- phone numbers (mobile and home), nicely formatted, do not show 'H' and 'M' if no data is present. Make 'H' / 'M' translatable (or better use small icon)
- address from new address object, nicely formatted in Street, zip / city, country, line feed for each  
- email (with mailto link)
- active since
- last login
### 1.2 Helper List for admins
If a user is an administrator, the helper list should show all circle members regardless of their settings. Additional columns should be:
- Help provide (count of completed tasks or supplies of this helper)
- Last help provided on (show date of last task and make it clickable to open that task)

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/13284279/900f5f28-daf3-11e5-9da1-b465abdae3cb.png)

## 2. Organizers
This list has the function to give quick access to the key people of a circle. It should list all circle admins plus work group organizers. Columns are:
- small initials icon & name, which links to the public profile page (hover over should work correctly on each line)
- working groups the person is organizer of (leave blank if admin only), column title should be 'Organizes'.
- phone / address / email as above
- Last login (no need for active since)

Massively useful would be an export or print function of both lists, but that we should track in a separate feature request.

**Comment by kristysnet** [comment]
@dottorer I updated the feature/helper-list branch to reflect your specifications for the public helper list (currently called Public Members) and the admin-only list (currently called Helper list). If you could take a look and let me know what you think, that would be great. I'll be working on the Organizers part tomorrow.

**Comment by dottorer** [comment]
I will take a look today. One thought was there was ideally only one link in the left nav named 'helper list'. If your are admin, you get the full set. If you are not admin, you get the public list only. Does that make sense?

**Comment by kristysnet** [comment]
yes, they are basically the same thing with just a few columns difference and only admins can see non-public members. Its just the link names / headers that are different. We can make them the same if you want.

**Comment by dottorer** [comment]
@kristysnet Looked at the branch and it is getting close! One thing I noticed is that we should use the small initials icon (sized like in the top menu bar) for each user. The real big one is to bulky. Will do some more detailed visibility testing next.

![image](https://cloud.githubusercontent.com/assets/14217285/13497235/95553d7e-e154-11e5-8b1b-c188bef5d27f.png)

Also last col should be shorter titled 'Last helped'. I will do the translations once it is completed and in master.
