### ISSUE TITLE
Ukrainian refugees

### ISSUE THREAD

**Issue by pjfanning** [lale-help/lale-help#515]
Hi @dottorer,
I'm not sure what the status of the Lale web site is. I've just seen a news story on the BBC about the rules for Ukrainian refugees and UK residents need to sponsor refugees - they won't be allowed into UK without a sponsor. Other European countries have welcoming policies but some Ukrainians may want to go to UK. I'm wondering if Lale site could be used to allow UK residents to find Ukrainian refugees to sponsor and vice versa.

https://www.bbc.com/news/60735121 details the requirement:
```
In the "first phase" of the scheme, people will need the name of a Ukrainian individual or family they wish to sponsor.
```

**Comment by dottorer** [comment]
Hi PJ, great to hear from you. The Lale platform is indeed currently in use
in some cases to coordinate help for Ukrainian refugees. By far and large,
we have shut down the use of the platform as there wasn't a need anymore to
coordinate tasks for refugees. As for your specific use case, I would
assume that quickly there will be platforms more suitable to coordinate
your needs, IT moves fast in situations like this. It seems that there are
already clear requirements to register and be matched and some
organisations are working to do the matches. Lale would likely be more
suited to coordinate needs such as targeted donation of clothes, etc. but
even that is usually handled by the organisations at hand.

The situation is not good, but my experience over the last 6+ years with
coordination volunteers is that it is often very difficult to optimize and
some of the existing actors are already pretty good at getting it done.
Just my two cents...

That said: I friend of mine has in under two weeks created
https://www.instagram.com/europeanpeoplemedia/ and hired 7 Ukrainians to
create content. Maybe this can be of help in the UK as well...

All the best!

Ralf Schroeder

<https://about.me/ralf.schroeder?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by pjfanning** [comment]
Thanks @dottorer for the feedback. I'm sure someone is working on a solution to help match volunteers with refugees. I will close this.

**Comment by pjfanning** [comment]
for reference, https://help.gov.ua/ seems to be a good resource
