### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by phil-monroe** [lale-help/lale-help#53]
Ability to store and link files to various models. Files will be stored on Amazon S3 in the EU. 

Models with Files: 
- User/Volunteer 
- Action Task 
- Supply Task

**Comment by dottorer** [comment]
Assigning to Phil what he is working on already as mvp1 work.

**Comment by dottorer** [comment]
Per dev chat 3/15 @phil-monroe will take a stab at this. Initially we will use the file storage for helper photos, but also then for attachments to tasks, supplies. We will open separate issues for each usage of files.

**Comment by phil-monroe** [comment]
Some notes after digging in a bit deeper:

Encryption is possible with S3, but I recommend keeping the encryption keys 
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingEncryption.html

I think I'm leaning towards using the Server-Side Encryption with Customer-Provided Encryption Keys option as that keeps access control done through the app and files cannot be lost if our AWS account gets hacked.

As for antivirus: There also seems to be this nifty API. (also EU compatible!)
https://scanii.com/

**Comment by dottorer** [comment]
Scanii looks slick and painfree to integrate, just a matter of cost and we can consider this benefit later. Thanks for finding it.

For encryption, SSL for in-transit and server-side wirh Lale keys for at rest is a good option, sounds like...

**Comment by dottorer** [comment]
@phil-monroe Tested the files a bit today. Really nice work! 

Here is some feedback on the points we talked about:

* And I was curious what the public / private on the document does? Does it restrict access to the owner of the link only?
* Showing the circle docs in a box on the right is a good start but I think it will grow quickly from there into some from of a document repository. We might consider an item in the leftnav for 'Documents' and have a list view of all documents / links (tabbed). I will come up with a design for that soon.
* Would it be possible to show the document type and size in the listing somehow? If we only show the 'nice name' which is great for usability it could be confusing quickly.
* I was thinking a bit more about how we could bring attachments a bit more to life in a task so people are drawn to it. Here is an example of what I mean: 
[Uploading Anfrage gärtnern var2.pdf…]()
Maybe the content could be shown as a thumbnail somehow, possibly in a hover over (see examples):
![image](https://cloud.githubusercontent.com/assets/14217285/14943258/0b5de1a8-0fd4-11e6-81cc-891c03c7eeb2.png). Let me know if you have any good ideas and if its doable in reasonable effort.

Lastly, once you merge this into Master, I will do the translations and we can push to PROD soon.

**Comment by dottorer** [comment]
@phil-monroe nice work on documents. Few thoughts:

- with the new 'Documents' in the leftnav (aka the doc center), we dont need it in the circle admin pages anymore. Admin can add / edit files in the doc center direclty. Docs added here will be on the circle scope. Normal helper can only view docs here.
- all docs (files or links) should open in a separate tab. The default browser action per doctype should be called upon.
- we will have a 'Documents' tab for the workgroup to add work group level docs. Those will be then displayed in the doc center on a separate tab.
- also, while we are cleaning up, we should remove the 'Extended settings' tab with its one checkbox and move that to the 'Invite' tab.
- it seems that the uploaded time stamp is off by 2 hours.
- we likely should remove the documents box from the circle dashboard now that we have the larger doc center...

**Comment by phil-monroe** [comment]
- [x] _with the new 'Documents' in the leftnav (aka the doc center), we dont need it in the circle admin pages anymore. Admin can add / edit files in the doc center direclty. Docs added here will be on the circle scope. Normal helper can only view docs here._

- [x] _all docs (files or links) should open in a separate tab. The default browser action per doctype should be called upon._
  - By default, file data will be sent with disposition `inline`, which tells the browser to display the file if it can, otherwise the file will be downloaded. https://github.com/lale-help/lale-help/blob/master/app/controllers/files_controller.rb#L15

- [ ] _we will have a 'Documents' tab for the workgroup to add work group level docs. Those will be then displayed in the doc center on a separate tab._

- [x] _also, while we are cleaning up, we should remove the 'Extended settings' tab with its one checkbox and move that to the 'Invite' tab._

- [ ] it seems that the uploaded time stamp is off by 2 hours.

- [x] we likely should remove the documents box from the circle dashboard now that we have the larger doc center...

**Comment by dottorer** [comment]
This is working well now in PROD. Thanks @phil-monroe !!!

Tracking all further work on documents in separate issues...
