### ISSUE TITLE
OS X setup error

### ISSUE THREAD

**Issue by bernhardvogler** [lale-help/lale-help#57]
```
bash-3.2$ ./bin/setup-osx.sh
== Updating Homebrew ==
error: The following untracked working tree files would be overwritten by merge:
	Library/Formula/ldid.rb
	Library/Formula/mosml.rb
	Library/Formula/pdf2svg.rb
	Library/Formula/ppl.rb
	Library/Formula/smpeg.rb
Please move or remove them before you can merge.
Aborting
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master
```

**Comment by dottorer** [comment]
Hi Phil, Bernhard joined us new and is looking at getting the project to fly. Could you help him out?

**Comment by phil-monroe** [comment]
@bernhardvogler: seems like you have some manual changes to files in the homebrew directory. Homebrew uses git under the hood to keep track of formula updates and seems there are conflicts with some manual changes. Take a look at these links:

- http://stackoverflow.com/questions/10762859/brew-update-the-following-untracked-working-tree-files-would-be-overwritten-by
- https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Common-Issues.md#brew-update-complains-about-untracked-working-tree-files

**Comment by bernhardvogler** [comment]
@phil-monroe Thanks for the quick help! This fixed it:

```
$ cd /usr/local
$ git fetch origin
$ git reset --hard origin/master
```
(see http://stackoverflow.com/a/12031907/2858480)

Is there a place to document this fix, like in some technical FAQ or so?

**Comment by bernhardvogler** [comment]
BTW, I had to install bundler using ```gem install bundler``` before I was able to successfully run ```bundle install -j8 --path .bundle```.
(see http://stackoverflow.com/a/32123466/2858480)

**Comment by bernhardvogler** [comment]
Next issue I run into:
```
$ bin/rake db:init
2015-11-05 11:17:34.163065 +0100  INFO [PID-46102] [TID-owiswyv3s] logger initialized (level: INFO, lograge: true)
rake aborted!
KeyError: key not found: "SMTP_ADDRESS"
/Users/bernhard/dev/lale-help/config/application.rb:21:in `fetch'
/Users/bernhard/dev/lale-help/config/application.rb:21:in `<class:Application>'
/Users/bernhard/dev/lale-help/config/application.rb:8:in `<module:LaleHelp>'
/Users/bernhard/dev/lale-help/config/application.rb:7:in `<top (required)>'
/Users/bernhard/dev/lale-help/Rakefile:4:in `require'
/Users/bernhard/dev/lale-help/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by enricoag1982** [comment]
I'm working with Bernhard to solve it.

**Comment by dottorer** [comment]
Assigned to Enrico...thanks!

**Comment by phil-monroe** [comment]
The project uses a file called `.env` that holds environment variables to be used when loading dynamic configuration. I've updated the example file `.env.example` with a list of required environment variables.

**Comment by posixpascal** [comment]
Closed as I reproduced and fixed this using the given example .env file.
