### ISSUE TITLE
Create session time out

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#63]
We should probably introduce a session time out of 10 minutes to kick users out of they have an inactive period. Right now the session seems to be open without end.

**Comment by dottorer** [comment]
@phil-monroe  - do we need this for mvp1? Seems like the sessions are endless right now...thoughts?

**Comment by phil-monroe** [comment]
It's a 1 line config setting, so what would you prefer?

**Comment by dottorer** [comment]
@phil-monroe Let's set this to 15 mins....
