### ISSUE TITLE
Expose missing strings for translations

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#74]
Looking at @pierresauvignon first cut of French translations, I noticed that we likely have a few field not exposed in the yml files yet. Could we expose them? Screenshots below.

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/11464970/16da4804-9735-11e5-88ee-4328c1da2e47.png)

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/11464973/1f582d5c-9735-11e5-89e2-727ca562f995.png)

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/11464979/2ae6b4ae-9735-11e5-9c83-748dee3c71f9.png)

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/11835568/e2b78cce-a3d4-11e5-99f0-b31bd82fff7c.png)

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/11835586/0469ced6-a3d5-11e5-8c87-aa241792f4d0.png)

**Comment by diegoaad** [comment]
<img width="1094" alt="screen shot 2015-12-21 at 09 44 38" src="https://cloud.githubusercontent.com/assets/4204139/11926819/19690fee-a7c8-11e5-925e-29a53122ede8.png">

**Comment by dottorer** [comment]
I think this is now obsolete until we see the new translation architecture via activeadmin. Then I can go and translate all into German and we will quickly see the missing strings. Then I re-open specific issues as they come up.
