### ISSUE TITLE
Set header color to 'blue' if task is fully staffed with volunteers.

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#76]
Our current workflow marks the color of the task header green once it is completed. This is powerful, but another really important state transition is when a task / supply becomes fully allocated (i.e. 3 of 3 helpers have signed up etc). We should use the visual cue of header color here as well and set it to a nice dark blue. This was a request from a demo audience.

We have the code to set it green somewhere, might be easy to set it to blue as well. ALso, if a task becomes un-allocated, we need to go back to gray.

**Comment by dottorer** [comment]
Here is the green header look for reference.

![supplies - details 2 of 2 2x](https://cloud.githubusercontent.com/assets/14217285/11653826/3caed7d0-9da1-11e5-935c-74bf2e78abbb.png)

**Comment by dottorer** [comment]
@diegoaad can maybe work with @anvarik to see how we can mimik the 'done' logic turning it green to turn it blue on full assignment. We only have three states: open (grey), fully assigned (blue) and done (green). State transitions to and from are possible...

**Comment by diegoaad** [comment]
@dottorer I assigned the issue to myself, will work on that and get help from @anvarik.

**Comment by dottorer** [comment]
@kristysnet We already have a way to determine the status of a status and we set the color of the little dot icon accordingly. I guess this issue is then only to color the header portion of the task page in the same color. What do you think?

**Comment by phil-monroe** [comment]
should be closed in #144

**Comment by dottorer** [comment]
Looks great - thanks!
