### ISSUE TITLE
Ability to edit and delete posts

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#80]
An author should have the ability to edit a post and even delete it. This should appear as a small option in the hover over text for commenter name and comment time. If easier for deletions, we can keep the comment in the database and just suppress its rendering if 'is_removed=true'.

**Comment by posixpascal** [comment]
Do you mean comments by posts?

**Comment by dottorer** [comment]
@nolanchan not sure how difficult this one is with a smooth ux appearance, just like they do in Slack or Skype or other chats...let me know what you think.

**Comment by dottorer** [comment]
Hi @kristysnet this was suitably reported by pilot users today. I was thinking if you are looking at the Lale Bot inserting comments, maybe this is something to consider as well. 

UX wise, the edit and delete option would appear on hover over on of of your own comments.

![image](https://cloud.githubusercontent.com/assets/14217285/14937375/e2e9eae2-0f05-11e6-9844-393e2071251c.png)

We already reveal the commenter name and time there, but the name is clear if its your comment. We could instead of the name show "edit" and "remove" links in the same font there.

Delete would do a verification like:
![image](https://cloud.githubusercontent.com/assets/14217285/14937396/51e56200-0f06-11e6-9fb8-572b24dfc803.png)

Edit might be tricky since we don't have the text box available. If you find a way to edit it in place (i.e. make the read-only comment editable with a cancel / save option), we might need to do a modal popup to edit it.  

I like the way this is handled in slack (obviously) so anything close to that would be great.

Can you give me an idea of how hard / how much work this would be? Thanks!

And it was great seeing you / meeting in person this week :-)

**Comment by dottorer** [comment]
@kristysnet Hi Kristy, this is coming up frequently from user and hopefully something we gould do quickly. What do you think?

**Comment by dottorer** [comment]
@kristysnet Small nit: when I edit a comment and change '1111' to '2222', but then hit cancel, I am taken out of the edit dialog (correct). When I hit edit again, the value shown i now '2222', but it should still be '1111' since we cancelled out. Can we fix that?

**Comment by kristysnet** [comment]
This should be done now. Please reopen if there is anything else needed.

**Comment by dottorer** [comment]
@kristysnet Done and done and awesome - thanks!
