### ISSUE TITLE
Allow work groups as 'private'

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#81]
We need to provide a flag on work groups to be marked 'private'. This means thats only members of that group and the circle admins can see them in the left nav. 

They should be marked with a little * or key symbol or something in the left nav to show that they are private. This is very powerful for groups to contain sensitive discussion to a small group of people.

Given that the groups are hidden to non members, people cannot just sign up. Therefore we need to allow the group organizer to add/remove people to the group.

**Comment by dottorer** [comment]
This is coming up more and more as a must-have with the pilot groups. 

@phil-monroe how difficult would it be to:
(a) mark a group private and show it in the left nav only clickable to members (and a little key icon).
(b) instead of join/leave button, we need to have a prompt of all circle members to add them to the group and remove them from the group.

**Comment by dottorer** [comment]
Hey there, this one would be super sweet for pilot with the circles. Would it be a lot of work to come up with a meaningful prompt to add and remove circle members to a private group?

**Comment by dottorer** [comment]
@phil-monroe moving this one into mvp1 since I heard 3 pilot circles mentioning it as a main barrier for them to really use the platform. They just have private stuff to organize. Therefore trying to get it into mvp1. Let me know what you think.

Good news: If we have a control that allows us to pick any circle member to become part of the group, we can also use that type of helper prompt in #141 later.

**Comment by phil-monroe** [comment]
Should be done, just in need of some translations.

**Comment by phil-monroe** [comment]
Whoops, check that. I need to add a way to manage members still...

**Comment by dottorer** [comment]
Really awesome first cut by @phil-monroe  on the private work groups - looking nice!! I have done a first cut a translations and deployed in STG. Did some initial testing. Some nits so far:
1. If a group is private, the button 'Join' should not be offered to the users. They can really only be in the group if they have been added by the organizer or admin.
2. The button 'Leave' still makes sense as they could self-opt out.
3. The title of the 'basic settings' page is a bit close to the tab bar.

**Comment by phil-monroe** [comment]
Should be good to ship!
