### ISSUE TITLE
Add unique identifier to circle for billing purposes

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#85]
In order to uniquely identify a circle for contact and billing purposes, we need to create an identifier like a customer number. This number should not be numeric but be a long string. 

It should be created at initial circle creation. It should be displayed, but not editable on the circle edit page.

**Comment by posixpascal** [comment]
I added a `unique_identifier` variable to the Circle model which gets initialized once before creation.
I'll make a pull request so other people can see it.

**Comment by dottorer** [comment]
That's excellent, what is it's format? Suitable for use in #86 ?

**Comment by posixpascal** [comment]
Basically it looks like this at the moment:

`b9208b6bb63e130eee73d4e7e30fdc8c967503e182c373473e28ad86176b2c0f`.

I use the SecureRandom.hex method which will output a 32 character long alphanumerical string.
Then I use another SecureRandom.hex to create 64 characters and store them to the circle.

It's suitable for #86, although it's a bit long. I'd suggest adding a `Copy Link` or `Invite per Facebook/Whatsapp/Mail` Button.

**Comment by dottorer** [comment]
This is a good unique ID, although long for our usage for invites. 'Copy Link' next to it can do the trick for now though.

**Comment by posixpascal** [comment]
We can trim it down to something like this:

`5b9208b6b` if you want to. Then we should hide the circle.id in there to avoid collision.

**Comment by dottorer** [comment]
That looks much neater like a tinyURL almost. Could go very well in the invite link. Can we ensure uniqueness or would it be a simple rtrim?

**Comment by posixpascal** [comment]
Yes if we add the circle ID to that unique string.

**Comment by dottorer** [comment]
Yes, totally. That would work nicely!

**Comment by dottorer** [comment]
At this moment, we put this issue on hold until we have a cleared picture of the billing infrastructure. We have a unique URL for the invite flow already by circle Id and name.

Unhooking from mvp1.

**Comment by dottorer** [comment]
No longer needed....closing.
