### ISSUE TITLE
Provide URL to invite new members to circle

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#86]
During the signup process, new helpers need to be able to join a specific circle. They might have discovered a circle on the map or by location, but more often they will have been directly invited by the circle admin.

**Comment by dottorer** [comment]
We need to offer an external URL as shown in Stephane's mockups. In order to avoid people manipulating the URL and inviting to other circles, this URL should not use the circle number, but its unique identifier as defined in #85.

![single page form - create circle 2 of 2 2x](https://cloud.githubusercontent.com/assets/14217285/11892219/4b83712c-a566-11e5-867e-a0d497e75fc1.png)

**Comment by phil-monroe** [comment]
Would a link like the following be too hideous?

`http://lale.help/token/4a17b05b2fc5d10157025213d39b8fa325fa51a3fbbcc0a356ac9050f0d7f7e327090bfd70f7cabc01c49178b5fbdefa3722a71b1a7c1e20f766c3498f414252 `

**Comment by phil-monroe** [comment]
The more I think about it... yes it is too gross looking and there is no need to to have a secure token that can't be brute forced for the act of inviting people... A much cleaner way just dawned on me that will use links of the form:

```
https://app.lale.help/join/CIRCLE_ID
```

No need to complicate this...

**Comment by dottorer** [comment]
Totally, I think Pascal proposed a perfect medium ground in #85 .

We have the long string for a circle ID, we truncate it and add the circle seq number. This way it is hard to forge for inviting but easy enough to copy...makes sense?

**Comment by posixpascal** [comment]
Yes.  I would use a little cryptic id instead of the circle id. We could
however let the circle admins verify users after they joined that way
sticking to the circle id instead of the cryptic id is fine as well
Am 14.01.2016 8:47 vorm. schrieb "Ralf Schroeder" <notifications@github.com

**Comment by dottorer** [comment]
We will definitely need to have the circle admin verify / accept new registrations before they become fully active. That workflow has been mentioned several times by admins, but we don't have capacity right now in mvp1 to add it.  Unless we send a notification to the admin when someone joins with a push button to 'activate account'. Until then a new registree would be able to log in but not see much in the system.

**Comment by phil-monroe** [comment]
Since there will be a for people to be verified in the future, does the if need to be cryptic? Here is some food for thought:

https://gist.github.com/cdmwebs/1209732

**Comment by dottorer** [comment]
Well, I understand the variations of URL generation in ruby better now, slugs and all. 
I guess in general all URLs include the object and instance id like 'https://staging.lale.help/circles/3'. If we have a review step by the admin, then I guess no one could slip in by faking the URL. And they can only get to a full task if they have a valid sessions for that circle, right? 

So, for now unless we care about the security aspect of the review step, we could take the URL is ruby gives it to us. Leaves us a bit exposed but guess ok for mvp1.

**Comment by phil-monroe** [comment]
Well if you are concerned with people randomly joining a circle, than it should be cryptic. But that leaves me to question the standard sign up flow where a user looks for circles to join that are near them. If I can look up and join a circle by location, why not be able to easily generate a url to join said circle?

I think it all comes down to: how locked down joining a circle should be? Easy but requires approval? Invite only?

**Comment by dottorer** [comment]
Very good point. I think let's do non-cryptic simple URL but approval step by admin. Works for all cases.

**Comment by phil-monroe** [comment]
:+1:

**Comment by dottorer** [comment]
This is in mvp1 right now...
