### ISSUE TITLE
Improved rendering date / time control

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#87]
The currently used date picker has left some users stranded. We should leverage a more intuitive date picker that:
- only allows data selection, not entering in free form field
- drops down from the field when placing focus on it
- shows current day highlighted and selected day highlighted

**Comment by dottorer** [comment]
A good example of this is on open table (ex: http://www.opentable.de/wirtshaus-in-der-au-reservations-munchen).

![image](https://cloud.githubusercontent.com/assets/14217285/11892769/73264a10-a56b-11e5-80a7-d78994440e82.png)

**Comment by dottorer** [comment]
This example also has nice time picker right next to the date...

**Comment by posixpascal** [comment]
I used the bootstrap-material-datepicker at work lately:
http://t00rk.github.io/bootstrap-material-datetimepicker/

**Comment by dottorer** [comment]
The basic date picker looks good. Although the way it drops right out of the field in the example above is clean. Also, the multi step process to pick various elements is not initially clear.
   
I find the analog clock time picker weird and clunky when a simple drop down with 15 min increments can quicker select a time.

**Comment by dottorer** [comment]
I guess an important factor of the DTP would be the responsiveness on devices. Not sure which ones can work across platforms.

**Comment by posixpascal** [comment]
How about using the `<input type="date" /> `?

and a regular datepicker plugin as a fallback. 
Benefit of <input type="date" /> is that it let's mobile users use their native date picker.

**Comment by dottorer** [comment]
I have to admit I need to leave this to the UI experts to decide, bit out of my tech depth. 

The thought is that several users have struggled in entering the right date / time. The example above seemed very crisp and clean. This issue is related anyways to the improvement in #68 where we need to think about how we can offer the 3 forms of due dates ("by date", "at time" and "in period") in an intuitive way. DTP is a sub-element of this interaction.

I think we might need @stephanerangaya help to define an overall UX for this specific interaction element. That might drive which DTP to consider...

**Comment by dottorer** [comment]
@phillipoertel Merging in requirements from dup #68 which I am closing. Will add Taks Rabbit example here for discussion.

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/13637295/e49dc066-e606-11e5-9544-6c65dfeef76e.png)

Adding example of powerful yet simple and intuitive "task time picker". More investment than we can stomach, but offers the following:
1. shows week day, date and point in time that is current selected clearly
2. offers 'next week' as quickly scrollable selection window (where most tasks will happen)
3. allows quick selection of predefined time block on a day (morning / afternoon /evening / anytime)
4. allows also specifying a concrete time (for doctor appt for example).

We would need to adapt this to suit our needs, but this is a control well done (and heavily invested in I am sure).

**Comment by phillipoertel** [comment]
my first stab is available at http://lale-help-dev.herokuapp.com (soon to be http://development.lale.help).

**Comment by dottorer** [comment]
Definitely an improvement! Few thoughts on first glance:

1. time default value is 0:00 which makes sense if we ignore time and just want a date. However, anytime we specify a time we need to scroll 4-5 times before we get to noon. Not sure how to resolve this in this control but something we need to strike a balance on. Ideally, we could check [x] time to set it and otherwise just display the date.
2. The 'time type' selector drop down is taller than the date fields which makes it look a bit off alignment.
3. I can't save any setting as it says 'please correct the errors below' but no errors are shown.
4. I need to think about the 2-col layout of the page whic start looking wierdly stretched. Maybe something closer to Stephane's mockup is possible eventually:

![image](https://cloud.githubusercontent.com/assets/14217285/13706520/ada290c8-e7a5-11e5-8516-c25758269b17.png)

Will play with it some more, but i like the direction.

**Comment by phillipoertel** [comment]
Changes as discussed with Ralf:
- use separate date and time input for due date. time input should optional
- same goes for end date/time

**Comment by phillipoertel** [comment]
I just deployed a new iteration on **dev**. Some remarks, referring to your feedback numbers above:

== 0. ==

**Important**: please test with Firefox if the calendar renders incorrectly. There are some global CSS rules in lale which cause parts of the calendar to render outside it's container, and I still need to find and adapt them.

== 1. == 

- Right now it's best to test the UI only with new tasks; existing tasks without time currently store 00:00, which is then displayed in the time field, that's confusing. I would migrated those cases to NULL later. 
- the time input fields are now always shown, but with a placeholder text (optional).
- I set the default time of the time picker to 12:00.

== 2. ==

- right now all selector drop downs are a little taller than the text input fields; this will need to be adapted globally. I fixed the one we're looking at for the moment, so it doesn't distract us.

== 3. == 

- that's by intention: to save wasted effort, I'll adapt the backend only when the frontend fields and mechanics have been decided on.

== 4. ==

- I agree, the layout of the fields doesn't adapt well to different browser widths. I'm not paying attention to that right now; focusing on comprehensible and efficient input fields instead.
Btw. I believe it would also require some thought to adapt Stephane's design to different browser widths.

== 5. == 

I added the "time commitment" field again, just so we don't forget it.
Again, the order and layout of most fields needs to be improved.

**Comment by phillipoertel** [comment]
Review app: https://lale-help-stg-pr-251.herokuapp.com

**Comment by phillipoertel** [comment]
@dottorer I fixed the exploding date picker (caused by 2 different things), and added JS to handle the case "start date set to after due date". Since we didn't discuss what to do then, I kept the current behaviour, which moved the due date/time to be the same as start date/time.

Latest code is on the review app: https://lale-help-stg-pr-251.herokuapp.com

**Comment by phillipoertel** [comment]
There is a (minor) JS glitch in some cases, but I'm stopping here for now until we've discussed the current state.

**Comment by dottorer** [comment]
This looks good at the current stage and we can open new issues for any further work. Thanks!
