### ISSUE TITLE
Create public helper profile view page

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#89]
We need to create a view-only helper profile page with the current information:
* Personal data and contact info
* Skills

If a helper has specified their profile to be public, we should open their public profile when a user clicks on:
1. the image or initials circle
2. the helper name

**Comment by dottorer** [comment]
This is related to #19, just with the new styling.

Later we can provide a button on the helper profile view page to send a direct message to the helper and open a 1:1 discussion thread.

Maybe @stephanerangaya can mockup a version of a profile view page for us to go by.

**Comment by dottorer** [comment]
We should also show helper stats on the public profile:
- member since
- number of tasks completed, etc.

**Comment by dottorer** [comment]
Here is what we need to do for mvp1:

* Create a new 'public profile' view page, which is accessible to:
** all other helpers if the user has marked their profile as public
** to any circle admin
** to a group organizer where the user is a member
* the page is accessible by clicking on the user icon (e.g. the initial / photo circle) or the user's name (note that this monicker will also trigger the hover over popup from #38)

This page will list only the following profile fields: 
* firstname + lastname
* about me (in smaller font as a short intro max 300 chars)
* email / mobile phone / home phone
* address block with street, postal, city
* circles helper is member of
* roles helper has
* number of tasks / supplies completed
* member since 

Note that some of the info above is already rendered in the helper listing / directory so we can reuse the code from there.

@kristysnet let me know if this makes sense.
@stephanerangaya we haven't talked for a bit, but maybe this one could use some short turn around time mockup work to guide us. It should be a kind of 'business card' for the helper so it needs to look good...

**Comment by dottorer** [comment]
Lookng good, i noticed that when we dont have access to the profile, we display a flash message 'user cannot be read'. This is a bit confusing and we should just not have the icon be a link in case of non-public user profile. I mean wecshould not perform a clecik, then check if profile is public and then decline the view.

Makes sense?

**Comment by kristysnet** [comment]
@dottorer that makes sense. Question, should the user even show up in the list view if they can't be clicked?

**Comment by dottorer** [comment]
Yep, should be listed but not clickable...

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/13050873/73e19810-d3f6-11e5-94ac-00960ce4bec8.png)

Good first stab at the public user profile. This is one that the UX folks should be excited about styling, so inviting @amin-nas to maybe take a look? This is the page a helper see about another helper to gain insights. It is related to #38 which pops on on hover over for user to not navigate away form the current page when looking for contact info.
