### ISSUE TITLE
Allow more helpers to sign up for task than are required

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#98]
We need to allow to overallocate tasks with helper. If there are 2 needed, we might have 4 sign up in order to have some new helper shadow the work and learn. 

This will be also needed later when we implement the 'helper trust score' features.

**Comment by dottorer** [comment]
Also noted that overallocation is no problem from the email buttons when more helpers click 'yes'. However online once the required number is reached, no one can add themselves, which we should allow.

**Comment by phil-monroe** [comment]
Seems to be done to me. @dottorer feel free to reopen if you have any issues.
